### ISSUE TITLE
`iter8ctl describe` does not work if caller does not have cluster wide permission

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1002]
**Describe the bug**
`iter8ctl describe` should retrieve details of the latest experiment. However, it relies on cluster wide access so if a user has restricted access, the command fails.

**To Reproduce**
Observed in CIL environment where one is logged in as user.

```shell
$ iter8ctl describe
Error: experiments.iter8.tools is forbidden: User "IAM#cil1" cannot list resource "experiments" in API group "iter8.tools" at the cluster scope
```

Even restricted to a valid namespace, this fails:

```shell
$ iter8ctl describe -n staging-kalantar---us-ibm-com
Error: experiments.iter8.tools is forbidden: User "IAM#cil1" cannot list resource "experiments" in API group "iter8.tools" at the cluster scope
```

Even specifying the experiment is insufficient:

```shell
$ iter8ctl describe hello-experiment -n staging-kalantar---us-ibm-com
Error: experiments.iter8.tools is forbidden: User "IAM#cil1" cannot list resource "experiments" in API group "iter8.tools" at the cluster scope
```

**Expected behavior**
Should work even when role/rolebinding restricts access to single namespace. Suggest always look only in specified (`-n` option) or default namespace.

**Kubernetes environment (please provide the following information):**
Observed in CIL environment. Not sure how to reproduce in local clluster.

**Additional context**

**Comment by sriumcp** [comment]
I believe this is the problem line: https://github.com/iter8-tools/etc3/blob/24336608a7c00f6c5bdc6a8581fb040fb55a25b8/iter8ctl/experiment/experiment.go#L101

Using a namespace within the list options might be a possible fix for this.

**Comment by kalantar** [comment]
> I believe this is the problem line

I agree. I have a fix for this. I am not sure how I can reproduce this in a local cluster. Any ideas?

**Comment by kalantar** [comment]
Also, I've suggested we limit results to a single cluster. This is a change from our current behavior. Any thoughts?

**Comment by sriumcp** [comment]
> Also, I've suggested we limit results to a single cluster. This is a change from our current behavior. Any thoughts?

I don't understand the above.

Re: local cluster, I don't know if there's a way to run minikube or kind without the cluster-admin rights for the user. If our test-cases pass, and if your CIL use-case can be manually verified, we should be good to go.

**Comment by kalantar** [comment]
> > Also, I've suggested we limit results to a single cluster. This is a change from our current behavior. Any thoughts?

> I don't understand the above.

The current implementation of `iter8ctl describe` finds the most recent experiment from all namespaces. By using a namespace filter on the get api, we will be altering the behavior; it will be the most recent experiment in a single namespace.  I think this is ok. And probably clearer.

**Comment by kalantar** [comment]
@atinsood FYI

**Comment by sriumcp** [comment]
Ok. I was confused because your sentence said a `single cluster`; I now understand that you're referring to a `single namespace`.

Yes, this change is ok. However, this change affects not just describe, but also assert and debug subcommands, which is fine.

Also, we want to change this related behavior ... https://github.com/iter8-tools/etc3/blob/24336608a7c00f6c5bdc6a8581fb040fb55a25b8/iter8ctl/cmd/root.go#L45

`namespace` is never ignored. Either it is `default` (if left unspecified), or set to the specified namespace.

**Comment by kalantar** [comment]
>  we want to change this related behavior 

How do we want to change this? `namespace` is always set to something (as you mentioned).

**Comment by sriumcp** [comment]
> How do we want to change this? namespace is always set to something (as you mentioned).

1. First, we want to change the description in the help text (specifically, the line I pointed to and other such lines if any)
2. Second, in terms of how iter8ctl finds numargs (and sets latest to  true or false), we want to get it right. Currently, there is a logic for setting latest to true or false which based on number of positional arguments supplied to iter8ctl command. We will want to make sure this logic is correct (either correct as is, or after appropriate fixes).

**Comment by kalantar** [comment]
> Second, in terms of how iter8ctl finds numargs (and sets latest to true or false)

I tested this manually. The namespace args are removed before this calculation is done. It works perfectly without change.

**Comment by kalantar** [comment]
Our solution may not be sufficient for CIL. We've set the default to `default`. @atinsood will this work?  https://github.ibm.com/cloud-innovation-lab/issue-tracker/issues/425 suggests not.

@sriumcp CIL is defining a kubeconfig with a context set to a namespace other than default. Are you aware of a way to determine the namespace of the current context instead of using `default`?

**Comment by sriumcp** [comment]
The simplest solution I can think of is, export the value of default from kubeconfig context to an env variable, and then use this env variable as part of other tools (including `iter8ctl` and also perhaps `kubectl`).

It is possible that `kubectl` might have some command to extract this context info, so setting of the env variable could be potentially simplified.

***

I think `iter8ctl` ultimately does get its context from the kubeconfig file. We can also investigate how to set the default value based on this context (we need to look into what `kubectl` would do for accomplishing this and replicate that logic).

**Comment by kalantar** [comment]
> This seems to be a special case.

I am not sure that it is. One can define a current context using a namespace and this would be typical in a shared cluster.  We have done most of our work in the context of a single cluster with admin access so we haven't thought about this. Further, it is not a relevant concern for etc3.

**Comment by kalantar** [comment]
I have found a way to determine this. It isn't pretty and I am sure there is a better way. I'll submit a PR and we can decide what to do.

**Comment by kalantar** [comment]
I am inclined to suggest we also allow a `--kubeconfig` option on iter8ctl; this is very common for kubernetes utilities.. I'll create separate issue for this.
