### ISSUE TITLE
Support `--kubeconfig=''` option for iter8ctl

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1005]
**Is your feature request related to a **problem**? Please describe the **problem**.**
It is a common option for kubernetes utilities as a way to specify a kube config file.

**Describe the feature/solution you'd like**
allow global option `--kubeconfig=''`

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Common approach to other kubernetes utilities

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
none

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
May not be a high priority. Maybe subsumed if we move to a kubectl plugin. This has not been determined.

**How will this feature be tested?**
- [ ] test case

**How will this feature be documented?**
- [ ] in iter8ctl help

**Comment by sriumcp** [comment]
This seems like a good idea.

https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client/config#GetConfig already supports this.
