### ISSUE TITLE
Allow interpolation in url parameter for metrics/collect

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1013]
**Is your feature request related to a **problem**? Please describe the **problem**.**
To better support deployment in multiple namespaces or to be able to deploy to a current context other than `default`, it would be beneficial to be able to allow the namespace to be a parameter everywhere. Today, we support this, for example, in run commands using `{{ .Namespace}}`. Allow this elsewhere that namespaces are commonly used.

**Describe the feature/solution you'd like**
Allow specification of `url` for `metrics/collect`using `{{.Namespace}}`. For example:

```yaml
url: http://hello.{{.Namespace}}:8080
```

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Easier to write experiments without resorting to a templating tool like helm.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Use this issue

**How will this feature be tested?**
- [ ] Added test case

**How will this feature be documented?**
- [ ] Update reference documentation

**Comment by sriumcp** [comment]
With v0.8, this problem can be trivially solved in Iter8Hub experiments, all of which will be Helm templated.

Wherever, namespace information needs to be included, it can be done so using {{ .Release.Namespace }} construct.
