### ISSUE TITLE
Modify controller's Helm chart to create a metrics' ConfigMap consistent with the new metrics definition

### ISSUE THREAD

**Issue by fabolive** [iter8-tools/iter8#102]
Our Helm chart and pre-compiled yaml installation files create the ConfigMap `iter8config-metrics` with our metrics definition.

**Comment by sriumcp** [comment]
@sushmarchandran Where is iter8-KUI picking up the configmap from? Are you working with your own private configmap?

**Comment by sushmarchandran** [comment]
@sriumcp iter8-KUI gets the configmap from the user's current kube config using `kubectl get configmaps -n iter8 iter8config-metrics -o yaml`

**Comment by sriumcp** [comment]
Ok... but how is the user's configmap populated in the cluster? Is it something iter8 installation already takes care of? Or do you manually create and populate the configmap?

**Comment by kalantar** [comment]
This is already fixed in https://github.com/iter8-tools/iter8/blob/master/install/helm/iter8-controller/templates/metrics/iter8_metrics.yaml

**Comment by sushmarchandran** [comment]
@sriumcp Installing iter8-controller should install the basic configmap from the helm chart. We do not manually create the configmap. After that, the user can edit it in KUI or directly using `kubectl edit`
