### ISSUE TITLE
iter8 assert should give insight into failing clause

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1043]
**Is your feature request related to a **problem**? Please describe the **problem**.**
`iter8 assert` evaluates a number of conditions and returns with either a response code of 0 or 1. This is great when used in a script. However, I don't get any insight into which assertion failed. Perhaps we need a `-v|--verbose` option that identifies success/failure per clause.  Alternatively, could just have failure message (sent to stderr) that indicates the failed clause.

**Describe the feature/solution you'd like**
Option to gain insight into which assertion fails

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Clear to user what the failure is

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Can do it here

**How will this feature be tested?**
- [ ] test cases

**How will this feature be documented?**
- [ ] part of usage documentation

**Comment by kalantar** [comment]
This seems to be present in log messages (`LOG_LEVEL=info`)

**Comment by sriumcp** [comment]
This seems like a basic requirement for assert. When it fails, it should print why it failed (what assertions were not satisfied) even without a -v switch.
