### ISSUE TITLE
Support `--app` flag in CLI

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1075]
**Describe the feature/solution you'd like**
Iter8 supports the notion of an *app* that can be specified for experiments.  This can be set by using `--set app=app` when generating the Kubernetes objects for an experiment with `iter8 gen k8s`. The app is denoted on each object using the `iter8.tools/app` key in `metadata.labels`.

Allow filtering of experiments by *app* in other commands.

- `iter8 k get --app app` lists only those with label `iter8.tools/app=app`
- `iter8 k delete --app app` (no `-e` specified) deletes the most recent experiment with label `iter8.tools/app=app`
- `iter8 k logs --app app` (no `-e` specified) prints logs of the most recent experiment with label `iter8.tools/app=app`
- `iter8 k report --app app` (no `-e` specified) creates report for the most recent experiment with label `iter8.tools/app=app`

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Users are able to subset experiments using a meaningful label as an alternative to the identifier.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Discussion can take place here.

**How will this feature be tested?**
Test cases needed

**How will this feature be documented?**
- Documented in command help
-

**Comment by sriumcp** [comment]
Done.
