### ISSUE TITLE
Update Install Directions

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#11]
When public we can simplify the install. The default install can be done by this command:

    kubectl apply \
    -f https://raw.githubusercontent.com/iter8-tools/iter8-analytics/master/install/kubernetes/iter8-analytics.yaml \
    -f https://raw.githubusercontent.com/iter8-tools/iter8-controller/master/install/iter8-controller.yaml

**Comment by kalantar** [comment]
I didn't realize that the knative install for iter8-analytics needed a different yaml fie. Should we be creating the default for this as well?

**Comment by fabolive** [comment]
Yes, that makes sense.

**Comment by fabolive** [comment]
Fixed by OR #13
