### ISSUE TITLE
Restructure Iter8 v0.8 experiment  folder to be in line with a Helm Chart

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1103]
Currently, an Iter8 experiment folder does not have any restrictions in terms of its structure (other than the fact that it needs to include an `experiment.yaml` file).

Restructure this so that it resembles a Helm Chart (in other words, Iter8 experiment will be a special type of Helm chart).

***

Key advantages of the above redesign are the following.

1. We can do away with `iter8 gen go` (for which the primary use case is code engine install). Simply modify the templates used for rendering instead to achieve the code engine install.
2. Inherits all the benefits of Helm charts, including the ability to use Helm directly to install experiments, embed experiments as Helm sub charts, and also documentation & versioning for the chart using `Chart.yaml`, and `README.md`, and documentation for templates using `templates/NOTES.txt`.

This does affect a few iter8 subcommands, but mainly `iter8 gen exp` ATM.

**Comment by kalantar** [comment]
How does this impact `iter8 gen k8s`?

**Comment by sriumcp** [comment]
Good Q. 

For now, I believe it does not impact `iter8 gen k8s` in anyway. 

Eventually, we will want to assess if it makes sense to  use Helm libraries directly (we also want to develop the design of the auto triggered experiments for A/B/n expts. before making radical changes to the k8s part; auto triggered experiments will provide additional reqs).

**Comment by kalantar** [comment]
It seems that restructuring as a helm chart means that experiment.yaml would be in the templates folder of a helm chart. Is this the thought? This would have implications on where `iter8 gen k8s` finds this.

**Comment by sriumcp** [comment]
`experiment.yaml` can continue to be where it is at the moment... 

However, `templates` folder should get `experiment.tpl`, and at least for code engine, `spec-secret.yaml`, `result-secret.yaml`, and `jobrun.yaml` (file names are just meant as examples).

Note that `experiment.yaml` is not an actual k8s manifest, unlike the `yaml` files inside `templates`.

To be really specific, we will have:

`iter8 gen exp -h` 

```shell
Read templates/experiment.tpl and render it as `experiment.yaml` file using values
```

***
For local experiments, Helm structure provides the `templates/experiment.tpl` file, and documentation.
***
For CE experiments, Helm structure also provides a way to install the experiment chart using Helm.
***
For K8s experiments, we can keep going with what we have and reassess if and how we want to leverage Helm (based on additional auto-trigger reqs which will arise as we design them).
