### ISSUE TITLE
Document how to update iter8 (brew)

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1144]
We should document the command to upgrade iter8:

    brew upgrade iter8

This seems important because iter8 changes frequently.

**Comment by sriumcp** [comment]
Perhaps also provide the upgrade commands for other ways (go and binaries -- even though they may identical to the install commands).

**Comment by kalantar** [comment]
@sriumcp this has been done, hasn't it?

**Comment by sriumcp** [comment]
Done.
