### ISSUE TITLE
Create a Iter8 Tekton task

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1145]
- [ ] Similar to the `kn` task, make sure an `Iter8` Tekton task shows up in the public Tekton task catalog, with a clear example.

**Comment by sriumcp** [comment]
1. Apparently, there is a separate RH OpenShift Pipelines task catalog. Find out where it is. Find out upstream relationship. Find out how to make Iter8 show up in the RH catalog.

**Comment by kalantar** [comment]
no longer relevant; use helm
