### ISSUE TITLE
`brew` test failure

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1162]
Iter8's Homebrew formula is located in the `.rb` files [in this repo](https://github.com/iter8-tools/homebrew-iter8).

While the formulae themselves seem ok, `brew` test is [failing in the automated GH actions](https://github.com/iter8-tools/homebrew-iter8/actions/workflows/brew.yaml) meant to update the `rb` files.

Strangely enough, the `brew` tests are working for me on my local laptop.

***

The brew formula needs to be adjusted so that it passes not just on local machine but also in GH action.

**Comment by kalantar** [comment]
brew no longer supported
