### ISSUE TITLE
`iter8 run` fails when using `--set duration=...`

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1164]
`iter8 run` fails when setting duration.

**Successful Execution**
```
$ iter8 run --set url=https://example.com
INFO[2022-02-08 16:41:03] Created the experiment.yaml file containing the experiment spec
INFO[2022-02-08 16:41:03] starting experiment run
INFO[2022-02-08 16:41:03] task 1: gen-load-and-collect-metrics-http : started
INFO[2022-02-08 16:41:15] task 1: gen-load-and-collect-metrics-http : completed
INFO[2022-02-08 16:41:15] experiment completed successfully
```

**Failed execution**
```
$ iter8 run --set url=https://example.com         --set duration=10s
INFO[2022-02-08 16:41:23] Created the experiment.yaml file containing the experiment spec
INFO[2022-02-08 16:41:23] starting experiment run
INFO[2022-02-08 16:41:23] task 1: gen-load-and-collect-metrics-http : started
ERRO[2022-02-08 16:41:26] fortio failed                                 stack-trace=below ...
::Trace:: error 400 for https://example.com: "Get \"https://example.com\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
ERRO[2022-02-08 16:41:26] failed to get results since fortio run was aborted
ERRO[2022-02-08 16:41:26] task 1: gen-load-and-collect-metrics-http : failure
ERRO[2022-02-08 16:41:26] exiting with code 1
```

**Comment by sriumcp** [comment]
I just ran the same thing above and here's what I get ... 

```shell
iter8 run --set url=https://example.com         --set duration=10s
INFO[2022-02-08 16:54:14] Created the experiment.yaml file containing the experiment spec 
INFO[2022-02-08 16:54:14] starting experiment run                      
INFO[2022-02-08 16:54:14] task 1: gen-load-and-collect-metrics-http : started 
INFO[2022-02-08 16:54:27] task 1: gen-load-and-collect-metrics-http : completed 
INFO[2022-02-08 16:54:27] experiment completed successfully
```

**Comment by sriumcp** [comment]
I recommend replacing `https://example.com` with  `https://httpbin.org/get`. The latter seems like a better site for testing purposes. The former is very glitchy.

**Comment by kalantar** [comment]
I continue to see the same behavior.  I upgraded `iter8` and tried again, including a new `iter8 hub` command.

```
$ iter8 run --set url=https://httpbin.org/get --set duration=10s
INFO[2022-02-08 17:12:50] Created the experiment.yaml file containing the experiment spec 
INFO[2022-02-08 17:12:50] starting experiment run                      
INFO[2022-02-08 17:12:50] task 1: gen-load-and-collect-metrics-http : started 
ERRO[2022-02-08 17:12:53] fortio failed                                 stack-trace=below ... 
::Trace:: error 400 for https://httpbin.org/get: "Get \"https://httpbin.org/get\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
ERRO[2022-02-08 17:12:53] failed to get results since fortio run was aborted 
ERRO[2022-02-08 17:12:53] task 1: gen-load-and-collect-metrics-http : failure 
ERRO[2022-02-08 17:12:53] exiting with code 1 
```

**Comment by kalantar** [comment]
It consistently works when not setting `duration`.

**Comment by sriumcp** [comment]
Ok yes. This looks like a bug. We will treat it as such.

**Comment by sriumcp** [comment]
My experiment.yaml looks like this... could you please share yours?

```yaml
# task 1: generate HTTP requests for application URL
# collect Iter8's built-in HTTP latency and error-related metrics
- task: gen-load-and-collect-metrics-http
  with:
    numRequests: 100
    duration: 10s
    qps: 8
    connections: 4
    errorRanges:
    - lower: 400
    versionInfo:
    - url: https://httpbin.org/get
```

**Comment by kalantar** [comment]
My experiment is:
```$ more experiment.yaml 
# task 1: generate HTTP requests for application URL
# collect Iter8's built-in HTTP latency and error-related metrics
- task: gen-load-and-collect-metrics-http
  with:
    duration: 10s
    versionInfo:
    - url: https://httpbin.org/get
```

**Comment by kalantar** [comment]
This seems related to `numRequests`. This works:

```shell
iter8 run --set url=https://httpbin.org/get --set duration=10s --set numQueries=100
```

In this case, experiment.yaml is:

```yaml
# task 1: generate HTTP requests for application URL
# collect Iter8's built-in HTTP latency and error-related metrics
- task: gen-load-and-collect-metrics-http
  with:
    numRequests: 100
    duration: 10s
    versionInfo:
    - url: https://httpbin.org/get
```

**Comment by kalantar** [comment]
I imagine `duration` and `numRequests` are usually not used together?

**Comment by sriumcp** [comment]
Perhaps you might find [this documentation](https://iter8.tools/0.8/tutorials/load-test-http/loadcharacteristics/) relevant?

**Comment by kalantar** [comment]
Thank you. Documentation is what I expected. I made comment and tried the combination because I noted that your experiment.yaml seemed to contain both (indeed, all defaults).  The issue seems to be with duration specified by itself without a numRequests to override it.

**Comment by sriumcp** [comment]
I am trying with `load-test-http` (not `load-test`), and it is consistently working for me. Perhaps you can try with the former in case you've been using the latter chart? 

***

I just realized, I'm using my local branch (used to create this PR #1163). I wonder if I changed anything for the better which is making it work as expected.

**Comment by kalantar** [comment]
> I am trying with load-test-http (not load-test), and it is consistently working for me.

I am doing the same. I do not think your `experiment.yaml` (above) is correct.  I do not think it should be filling in `numRequests: 100`. The user did not specify it. It is not specified in `values.yaml` (at least in master branch). 

I can try the PR branch as well.

**Comment by sriumcp** [comment]
> It is not specified in values.yaml (at least in master branch).

This is one of the things changing in the PR branch. Be that as it may, `experiment.yaml` with duration and without numRequests should work as promised.

**Comment by kalantar** [comment]
>> It is not specified in values.yaml (at least in master branch).

> This is one of the things changing in the PR branch.

This is a problem, I think. In order to get duration without `numQueries`, users will have to explicitly remove it since the documented behavior is that `numQueries` takes precedence.

**Comment by sriumcp** [comment]
We can null everything in the values.yaml file.

**Comment by kalantar** [comment]
I retried this today with the latest version of iter8. I am no longer able to reproduce this.
