### ISSUE TITLE
Match up Iter8 CLI version with chart version in launch command

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1174]
Suppose I have iter8 v0.9.

When I do an `iter8 launch -c load-test-http`, I want to use the latest version of `load-test-http` that is **compatible with Iter8 v0.9**. 

Of course, I need to be able to explicitly specify constraints on experiment chart version (which Helm chart downloader commands already enable us to do).

**Comment by sriumcp** [comment]
Here's a way to accomplish the above...
***
1. Bump up all  chart versions in `hub` to `0.9.0`.
2. Set a default chartVersionConstraint [here](https://github.com/iter8-tools/iter8/blob/df3bd3a86d613a97c373534c1d3479eb5410ebd9/cmd/hub.go#L77). If user supplies a version constraint, we should simply use that. If not, set it to be `string(base.MajorMinor) + ".x"` (for example, 0.9.x). This will ensure that the right chart is always pulled.

**Comment by kalantar** [comment]
> 3. Update docs test.

Which test? I don't see any tests of chartVersionConstraint except for unit tests in iter8.

**Comment by sriumcp** [comment]
Good point. I agree.. we don't need docs test update at all for this feature... removing my comment.

**Comment by sriumcp** [comment]
@kalantar Turns out tests in `docs` do need to be updated. They install `v0.9.0` of Iter8, and we want to use `v0.9.1` in them. Sorry about the back and forth on this... the repo structure/dependencies is something I'm yet to get used to :-)

Perhaps the PR that updates the `docs` test can also fix this issue, so that this issue is closed when that docs PR is merged?

**Comment by kalantar** [comment]
@sriumcp Is it possible to use `v0.9` instead?  Then there is less need to change this for every patch version.

**Comment by sriumcp** [comment]
`0.9` is supported using Brew. But not using other methods (note that v0.9 or 0.9 is not a valid semantic version tag which is why go install doesn't support it).

***

Could we reassess the question of patch vs. minor version after we migrate to GitHub Actions based tests?

**Comment by kalantar** [comment]
> Could we reassess the question of patch vs. minor version after we migrate to GitHub Actions based tests?

Yes. This will be an advantage of the action for our own testing.

**Comment by kalantar** [comment]
@sriumcp can you check permissions for the project. I do not seem to be able to assign a reviewer. It is ready for review.

**Comment by kalantar** [comment]
@sriumcp I think this has been done. Are there additional steps we need to take?

**Comment by sriumcp** [comment]
Yes, this is done. Besides, v0.10 works differently anyway (compared to v0.9) ... also we might go back and forth on this as we develop autox. Anyway, closing.
