### ISSUE TITLE
Chart template for readiness task

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1222]
Create template(s) to support readiness task added to load tests.

Some discussion in issue https://github.com/iter8-tools/iter8/issues/1190.

Summary is:

- enable user to identify a single resource for each kind: `--set ready.<kind>=a name`
- add a task to experiment for each resource
- user can set timeout with `--set ready.timeout=timeout`; applies to all resources
- user can set namespace with `--set ready.namespace=namespace`; applies to all resources
- allow user to extend to new resources types via `values.yaml`

**Comment by kalantar** [comment]
The readiness task needs to be documented. Using this issue to solicit input on how, where we want to do this in the documentation. The basic kubernetes usage tutorials for [http](https://iter8.tools/0.10/tutorials/load-test-http/kubernetesusage/) and [grpc](https://iter8.tools/0.10/tutorials/load-test-grpc/kubernetesusage/) can be modified to use the readiness task. 

Should we include a page in the user guide? We could specify the kinds one can use today (`service` and `deploy`). We could also provide more detailed documentation about how to add a new kind.  Perhaps using a knative service as an example.

@sriumcp @Alan-Cha

**Comment by sriumcp** [comment]
All of the above sounds great! Like with all other docs, we can also iterate of course on these docs.

**Comment by sriumcp** [comment]
Done.
