### ISSUE TITLE
Automatically launch experiments inside Kubernetes

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1252]
**Is your feature request related to a problem? Please describe.**
AutoX is the much discussed Iter8 feature which launches experiments (more accurately, Helm charts) automatically in Kubernetes when new versions of Kubernetes resources are created. Design this feature.

Note: Both FluxCD and ArgoCD support controllers that install and uninstall Helm charts. But their triggers are not Kubernetes objects... instead their triggers are other things, like COS and Git repo.

Note: Initial MVP for this feature will be demoed at Kubecon NA (chaos + Iter8 experimentation charts).

**Describe the solution you'd like**
Following is an **example** of how autox can be used to trigger experiments based on deployment changes.

## 1. Install autox

The following command installs the autox controller. In this example, the autox controller is installed in the `default` (Helm release) namespace, but automates experiments in the `test` namespace by watching for deployment objects. The name of the autox release is `autoxslos`. The name of the app is `hello`.

```shell
helm install autox iter8/autox \
--set `resources={deployment,service,ksvc}` \
--set `namespaces={default,prod,test}` \
--set groups.hello[0].repo=<some helm repo> \
--set groups.hello[0].chartName=<some chart name> \
--set groups.hello[0].valuesFileURL=<some URL from which to download a values file> \
--set groups.hello[1].repo=<some helm repo> \
--set groups.hello[1].chartName=<some chart name> \
--set groups.hello[1].valuesFileURL=<some URL from which to download a values file>
```

## 2. Trigger Helm chart install
The following creates a deployment with the app label which trigger the Helm chart install.
```shell
kubectl create deployment nginx --image=nginx -n test
kubectl label deploy/nginx iter8.tools/autox-group=hello -n test
```

Steps 1 and 2 are both required in order to trigger Helm chart installs.

## 3. Report experiment results (assuming one of the charts is an Iter8 experiment chart)

You can view the report for the autox launched experiment using familiar `iter8` commands.
```shell
iter8 k report --appName hello -n test
```

## 4. Remove an experiment group (= modifying the helm release)
You can `helm upgrade` the autox release in Step 1. Remove the groups that are not needed (make sure groups are 0 indexed properly .... 0, 1, 2, ...)

**Comment by sriumcp** [comment]
Experiment job/cron job/result secret will have experiment spec secret as the owner reference. This way, when `iter8 k delete` is invoked, it cleans up any experiment job/cron job/result secret associated with the experiment.

**Comment by sriumcp** [comment]
The above design necessitates the following changes to Iter8 experiment charts. 
  - service account must be introduced, perhaps as part of  `k-manifest` template to enable auto launch of experiments by autox. This should be accompanied by rbac permissions needed by this service account (specifically, creating jobs, and deleting the specific job/cronjob)
  - the job or cronjob that is used as the runner must use a different service account. This service account will have permissions needed to actually perform the experiment (e.g., reading spec secret and updating result secret).
  - for now, do not disable the required RBACs. We will disable RBACs subsequently (e.g., when we approach projects like code engine which require RBACs to be turned off)
  - enhance job/cronjon and result secret templates with owner refs
  - autox switch in manifests
  - remove istio from spec secret (refer to autox chart)
  - rename _task_rbac to _k_task_rbac

**Comment by kalantar** [comment]
done
