### ISSUE TITLE
Document install and assumptions for Iter8 A/B/n service

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1253]
A key challenge in A/B/n testing is associating metric values (computed in a front end service) to the version of the backend service that is responsible for the value. To solve this problem, Iter8 introduces an client SDK. This SDK provides, among other things, a version aware load balancing service that allows the client to be aware which version of a backend service requests are sent to.  

To support the load balancing feature, an Iter8 service, _iter8abn_, discovers versions and their associated endpoints.

In addition to providing a discovery service, _iter8abn_ is expected to mediate metrics writing to a metrics database. This feature is not discussed here.

Some relevant material: [discussion](https://github.com/iter8-tools/iter8/discussions/1068) and [initial design](https://github.com/sriumcp/iter8/tree/abn/mkdocs/docs/tutorials/abn).

**Comment by kalantar** [comment]
To identify new versions, _iter8abn_ watches for new resource instances that match some selection criteria: objects of a particular type with the label `app.kubernetes.io/name` matching an expected name. Version will be determined by the value of the label ` app.kubernetes.io/version`.  See Kubernetes [documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) which recommends these labels.

The load balancing function must either proxy messages for the client or provide the client with an endpoint to use for each request. In either case, an endpoint must be identified for each version. We assume that the endpoint is an object can can identified by looking for an instance of the specified endpoint resource type with a name/version matching those found for the version itself.

Therefore, to install the _iter8abn_ service use:

```shell
helm install iter8abn iter8/abn \
--set app.<app name>.resource=<resource type> \
--set app.<app name>.endpoint=<resource type>
...
```

Here _resource type_ is a Kubernetes [resource type](https://kubernetes.io/docs/reference/using-api/api-concepts/#standard-api-terminology), not a _kind_.

Alternative labels might be supported using `--set app.<app name>.label=<label>` and `--set app.<app name>.versionLabel=<label>` (not MVP).


A new version shouldn't be added to the load balancer function unless it _is_ ready. Most load balancers implement ongoing readiness checking and remove instances from the available set when the readiness checks fail. We should do the same; the user expects that the use of Iter8 will not degrade the behavior of their application.

To do so, no additional options should be necessary. We can leverage the information (from the templates) for the readiness task.

**Comment by sriumcp** [comment]
It would be helpful to see examples with concrete resource types.

If user 1 serves the ML model using Kubernetes deployments/services, and user 2 does so with Knative services, how will the the installation/labels differ between them? What is same... and what is different?

**Comment by kalantar** [comment]
Example of user serving ml model with deployments/services:
```shell
helm install iter8abn iter8/abn \
--set app.ml.resource=deployments \
--set app.ml.endpoint=services
```

Example using knative services:
```shell
helm install iter8abn iter8/abn \
--set app.ml.resource=ksvcs \
--set app.ml.endpoint=ksvcs
```

**Comment by kalantar** [comment]
The service must be able to watch resources and  identify versions. However, there is no need for this to be configured as part of the installation of the service. Doing so forces a reinstall for each new application being deployed. Furthermore, it requires knowledge of names in advance.  The primary need at install time is to identify the set of resource types that should be watched and in which namespaces.  This enables the install to define any necessary RBAC rules.

```shell
helm install iter8abn iter8/abn \
--set resources=<comma separated list resources> \
--set namespaces=<comma separated list namespaces>
```

The earlier comment about resources being Kubernetes resource types is incorrect. Really, these are just meaningful keywords that can be translated into a (group, version, resource type).

For example the following might be used several applications implemented as deployments/services and knative services in 2 namespaces:

```shell
helm install iter8abn iter8/abn \
--set resources="deployments,services,ksvcs" \
--set namespaces="foo,bar"
```

**Identifying Versions**
Identifying versions of an application is relevant only in the context of clients using the Iter8 SDK. A first interaction is to register interest in versions of a particular application. This enables the service to identify resources (of the types registered). The service can then identify versions by identifying the existence of resources with label `app.kubernetes.io/name` matching the registered name.  The label `app.kubernetes.io/version` identifies the version.

**Endpoints**
Identifying endpoints is really about identifying the information needed for the client to communicate. Implicit in the above approach is that it is a Kubernetes service. However, it is be easier for the client if the endpoint information was the information needed for communication; that is a URL and any necessary headers. An approach might be to expect annotations that provide this information. This may be fine for MVP.

**Readiness**
A simpler initial approach to readiness is to use an annotation that we expect to be set when the resources are available and correctly configured. This approach allows for a simple way to disable routing to a particular version. For example, a tag of `iter8-tools/ready` set to `true` would indicate the resource is ready.

**Comment by kalantar** [comment]
Replaced by https://github.com/iter8-tools/iter8/issues/1262
