### ISSUE TITLE
Upgrade Drivers to be able to read metric files

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1256]
**Is your feature request related to a problem? Please describe.**
In order to enable DB metrics-based experiments (like mirroring), driver needs to support reading not just experiment specs, but also metric specs. This feature needs to be created.

**Describe the solution you'd like**
```go
// Driver enables interacting with experiment result stored externally
type Driver interface {
	// ReadSpec reads the experiment spec
	ReadSpec() (ExperimentSpec, error)
	// ReadMetricsTemplate reads the metrics template
	ReadMetricsTemplate(provider string) (*template.Template, error)
	// ReadResult reads the experiment result
	ReadResult() (*ExperimentResult, error)
	// WriteResult writes the experiment result
	WriteResult(r *ExperimentResult) error
}
```

Implement the delta required in both FileDriver and KubeDriver.

**Comment by Alan-Cha** [comment]
Closed with #1260
