### ISSUE TITLE
Document client side use of Iter8 SDK

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1257]
Use gPRC to provide support for common front end service implementation languages with no language specific code.

**Comment by kalantar** [comment]
### Steps

These steps are not necessarily called one after another.

1. Connect to ABN service

    Before using the ABN service, it is necessary to connect to the service. This is language specific and may be non-trivial. As an example, see this [go example](https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L156-L176).

2. Lookup backend

    For each interaction with a backend service, lookup a version to use. The ABN service resolves the name of the backend service into an available version.

    ```shell
    rpc Lookup(Service) returns(TransactionVersion) {}

    message Service {
      // name of the (backend) service
      string name = 1;
      // version information to use if the ABN service is unable to identify any versions
      TransactionVersion defaultVersion = 2;
    }

    message TransactionVersion {
      // Name or identifier version. Is unique among versions of a service.
      string version = 1;
      // Transaction identifier; unique among all instances for this Service. Reserved for use by Iter8.
      string transaction = 2;
      // URL that should be used to communicate with this version of the service
      string URL = 3;
      // header information that should be used to communicate with this version of the service
      map<string,string> headers = 4;
    }
    ```

    The ABN service watches a set of resource types (configured at install time). The set of watched objects with label `app.kubernetes.io/name` equal to `Service.name` represent the objects related to `Service.name`. This set of obhjects can be partitioned in versions using the label `app.kubernetes.io/version`. A version is _available_ if there is no object with the annotation `iter8-tools/ready` set to `false` (either there are no such annotations or any that are present are `true`. It is preferable to have this annotation on every object but no requirement that it be the case). To identify the communication properties (`url` and `headers`) for a version, the service looks for the annotations `iter8-tools/endpoint-url` and `iter8-tools/endpoint-headers` on version objects. If there are multiple version objects with these annotations, one will be used; it is assumed that they are the same (it is an error if they are not, but the service will not check).

    Any instances without a `app.kubernetes.io/version` label are assumed to be members of a _default_ version. In this case, the default endpoint (passed in the request `Service` message) will be returned. If there are no instances in a version with endpoint annotations, the default endpoint will be returned.

3. Using `Endpoint.url` and `Endpoint.headers`, the client sends its request. The ABN service plays no role in this interaction.

4. Report metrics

    ```shell
    rpc writeMetric(MetricValue) returns (google.protobuf.Empty) {}

    message MetricValue {
      string label = 1;
      string value = 2;
      TransactionVersion version = 3;
      map<string,string> properties = 4;
    }
    ```

### Usage

```shell
// Connect with the ABN client. No detail given. See an [example](https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L156-L176).
client, clientError := getClient()

// Example initialization of a Service
// This includes identifying a default version to use when either ABN service is not available or it is unable to distinguish between versions.
const (
  BACKEND_NAME = "myBackend"
  BACKEND_DEFAULT_URL = "localhost:8080"
  BACKEND_DEFAULT_HEADERS = map[string]string{}
  BACKEND_DEFAULT_VERSION = "default"
)
myService := &Service{
  name = BACKEND_NAME,
  default = TransactionVersion {
    version = BACKEND_DEFAULT_VERSION,
    URL = BACKEND_DEFAULT_URL,
    headers = BACKEND_DEFAULT_HEADERS,
  },
}

...

// Example use of Lookup()
version := myService.defaultVersion
if !clientError {
  v, err := ABNServer.Lookup(myService)
  if !err {
    version := v
} 
send(version.URL, version.headers)

...
// Example use of WriteMetric().
if !clientError {
  metric := &MetricValue{ ... }
  _, err := ABNServer.WriteMetric(metric)
}
```

**Comment by sriumcp** [comment]
The [Golang gRPC hello world client example](https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_client/main.go) does not seem to bother with credentials. Given that: 
1. The `gRPC` authors themselves chose the easier (no-credentails/insecure) option as their first example, and 
2. Given that the service is intended to be cluster-local (not exposed to the external world, at least to begin with), and 
3. Given that service meshes like Istio can handle authentication/credentials outside of the service (even without the service handling authentication internally), and 
4. Given that we took the same approach for the Iter8 analytics service (cluster-local; no auth),
....
perhaps, the golang client side example can be simplified further by removing the authentication bits (which IMO adds needless complexity to the client side, while distracting from the core functionality that the sample is trying to demonstrate)... 

> This is language specific and may be non-trivial. As an example, see this [go example](https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L156-L176).

The client might still be non-trivial, but at least it would be simpler.

***

Part of the reason for complexity seems to be that we're trying to demonstrate both 1 and 2 below instead of demonstrating 1, the latter being the purpose of the example.
1. How to connect to A/B(/n) service
2. How to use various gRPC methods to supply auth credentials

**Comment by sriumcp** [comment]
A python client example for the Iter8 SDK is [here](https://github.com/sriumcp/iter8/blob/abn/samples/abn/deploy/frontend/frontend.py). 

I wanted to draw attention to the simplicity of this py example. IMO, the golang client example should not be any more complex than the py client. The idea is to create the simplest version of the client the demonstrates the core feature of the SDK, which I tried to accomplish with the py client.

**Comment by sriumcp** [comment]
```proto
rpc Lookup(Service) returns(TransactionVersion) {}

message Service {
  // name of the (backend) service
  string name = 1;
  // version information to use if the ABN service is unable to identify any versions
  TransactionVersion defaultVersion = 2;
}

message TransactionVersion {
  // Name or identifier version. Is unique among versions of a service.
  string version = 1;
  // Transaction identifier; unique among all instances for this Service. Reserved for use by Iter8.
  string transaction = 2;
  // URL that should be used to communicate with this version of the service
  string URL = 3;
  // header information that should be used to communicate with this version of the service
  map<string,string> headers = 4;
}
```

1. Is the following line correct?  Is TransactionVersion an object or a number? Also, could we please rename `TransactionVersion` to `VersionInfo` or simply `Version`? 
```
  TransactionVersion defaultVersion = 2;
```

2. What happened if the backend is a gRPC service? You will need more info to connect to it ... right?

**Comment by sriumcp** [comment]
Re:

```proto
rpc writeMetric(MetricValue) returns (google.protobuf.Empty) {}

message MetricValue {
  string label = 1;
  string value = 2;
  TransactionVersion version = 3;
  map<string,string> properties = 4;
}
```

I think we should eliminate properties. If there is a need for them, we can revisit later. For starters, their utility is not clear, and second, how is the user supposed to get them? Seems like needless complexity for questionable value.

**Comment by sriumcp** [comment]
> The ABN service watches a set of resource types (configured at install time). The set of watched objects with label app.kubernetes.io/name equal to Service.name represent the objects related to Service.name. This set of obhjects can be partitioned in versions using the label app.kubernetes.io/version. A version is available if there is no object with the annotation iter8-tools/ready set to false (either there are no such annotations or any that are present are true. It is preferable to have this annotation on every object but no requirement that it be the case). To identify the communication properties (url and headers) for a version, the service looks for the annotations iter8-tools/endpoint-url and iter8-tools/endpoint-headers on version objects. If there are multiple version objects with these annotations, one will be used; it is assumed that they are the same (it is an error if they are not, but the service will not check).

This is a bit hard to understand... perhaps
1. Starting with the assumption that one version = one kubernetes object (example, a simple K8s deployment object), 
2. K8s resource (example deployment) with the relevant annotations

might help?

***

Also, AFAIK, annotations are `map<string,string>`, which means the entire headers struct cannot be a single annotation; each header might need to be an annotation by itself.

**Comment by kalantar** [comment]
Some responses to the above
---
Regarding complexity of client connection to the service. My example reference was not meant to be an example of what we want. Rather just pointing out that the code might be complex. It depends on the assumptions about how the service is deployed which we haven't really thought about. I want to keep it simple but I wonder if the frontend might not be in the cluster which introduces a need for authentication/authorization.
---
Agree with suggestion that we start without the annotations for connection; you are right annotation is not suitable for all the headers.
---
Agree with suggestion to remove properties. I don't know what such properties might be. I just know that there are usually properties and I assume that the user might know some.
---
I have rewritten the description. I think it is now simpler/clearer. The suggestion that we focus on a single resource type (at least to start) may be reasonable. However, mislabeling is an easy mistake to make so having an implementation that does not restrict the user makes things more resilient. Further, if we restrict to a single resource type, the user will need to explicitly identify the resource type for each application. Currently, there is no need to do this (it just has to be among the watched types). I suggest we recommend the simplicity of a single type but support whatever is there. I am assuming it is not a lot more complex to do so. I do not think so.

**Comment by kalantar** [comment]
# A/B/n Testing

A key challenge in A/B/n testing is associating the values of business metrics (computed in a frontend service) with the version of a backend service responsible for the value. To address this challenge, Iter8 introduces an client SDK. This SDK provides, among other things, a (backend) version lookup service that exposes backend versions to the client.

In addition to providing a lookup service, the _ABN service_ mediates metric writing to a metrics database. The service provides this mediation to ensure association of metrics metric with the backend version and with a transaction identifier later used by Iter8 to evaluate SLOs.

## ABN Service

The ABN service provides a lookup service that resolves app names into an available version. When more than one available version is present, the lookup service will return a random version.

To implement the lookup behavior, the ABN service must be able to identify versions and determine if they are available (ie, ready).

### Approach

The ABN services watches a set of Kubernetes objects in a set of namespaces (specified at start time). The ABN service partitions observed objects into applications using the label `app.kubernetes.io/name`. Objects with no such label are ignored.
The ABN service further partions each set of application objects into versions using the label `app.kubernetes.io/version`. Any objects without this label are included in a default version.
An identified version is available if every object in the version partition with the annotatation `iter8-tools/ready` has it's value set to `true`.

Using a readiness annnotation is an initial approach. In addition to simplicity, it provides a mechanism for users to quickly and easily remove a version from consideration by marking it as unavailable.

### Install

The ABN service can be installed using the following helm install command:

```shell
helm install iter8abn iter8/abn \
--set resources=<list of resources> \
--set namespaces=<list of namespaces>
```

Here, a resource is an identifier that uniquely identifies a Kubernetes GVR. The set of identifies is specific to Iter8. Examples are `services`, `deployments`, and `ksvcs`.

### Helm Charts

TBD

## Client SDK

The client SDK will be implemented using a gRPC client so that many front end implementation languages might be easily supported. The ABN service will therefore be a gRPC service.

### Steps

1. Connect to ABN service

    The frontend (gRPC client) must connect to the ABN service. This is language specific. Initially, we assume users can write this themselves. It is may be non-trivial depending the deployment of the service. As an example, see this [go example](https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L156-L176).

2. Lookup version of backend

    Frontend requests a random available version of a backend service. The frontend makes this request for each call to the backend.

    ```shell
    rpc Lookup(Service) returns(Version) {}

    message Service {
      // name of the (backend) service
      string name = 1;
      // version information to use if the ABN service is unable to identify any versions
      Version defaultVersion = 2;
    }

    message Version {
      // Name or identifier of version; unique among versions of a service.
      string version = 1;
      // Transaction identifier; unique among all instances for this Service. 
      // Reserved for use by Iter8.
      string transaction = 2;
    }
    ```

3. Using `Verion.name`, frontend sends request to the backend. We assume the front end can determine how to send messages to a version of the backend service given the version name. This is an initial assumption that gives the greatest flexibility to support both HTTP and gRPC backends. Other appoaches (replying on user provided annotations on version objects inferencing) will be considered in the future.

4. Report metrics

    ```shell
    rpc writeMetric(MetricValue) returns (google.protobuf.Empty) {}

    message MetricValue {
      string label = 1;
      string value = 2;
      Version version = 3;
    }
    ```

### Sample Usage

```shell
// connect to ABN service; this is user implemented
abnClient, abnClientError := getClient()

...

// define Service message used for all lookup operations
// default values could also come from any kind of config
const (
  BACKEND_NAME = "myBackend"
  BACKEND_DEFAULT_VERSION = "A"
)
myService := &Service{
  name = BACKEND_NAME,
  default = Version {
    version = BACKEND_DEFAULT_VERSION,
  },
}

...

// Example use of Lookup()
version := myService.defaultVersion
if !abnClientError {
  v, err := ABNServer.Lookup(myService)
  if !err {
    version := v
} 

...

// Call backend; this is user implemented
call(version, message)

...

// 
if !abnClientError {
  // one for each computed metrics (user implemented):
  _, err := ABNServer.WriteMetric(&MetricValue{
                           label: l, // user defined metric label
                           value: v, // user computed metric value
                           version: version,
            )
}
```

**Comment by kalantar** [comment]
Replaced by https://github.com/iter8-tools/iter8/issues/1262
