### ISSUE TITLE
Kserve examples based on v0.10 support

### ISSUE THREAD

**Issue by cauwulixuan** [iter8-tools/iter8#1268]
**Is your feature request related to a problem? Please describe.**
I followed up tutorial here [kserve](https://iter8.tools/0.10/tutorials/integrations/kserve/), but the document showed that the examples were based on v0.7. I wonder whether 0.10 can be adapted to kserve? If so, can you update the documentation? Thanks a lot.

**Describe the solution you'd like**
Kserve examples based on v0.10 would be great to me.

**Comment by SebastianScherer88** [comment]
bump. any updated documentation for more recent iter8 version would be really useful. my team and i are looking at different progressive delivery tools for our ML platform, so any up-to-date guidance on how to apply this to 
- kserve >= 0.9 ([this seems to be out of date and still refer to kfserving from kubeflow](https://iter8.tools/0.13/tutorials/integrations/kserve/)) and/or 
- seldon-core (unless [this is still up-to-date](https://iter8.tools/0.13/tutorials/integrations/seldon/))

would be great.

**Comment by kalantar** [comment]
all tutorials have been updated to latest version
