### ISSUE TITLE
Multiple versions support for http task

### ISSUE THREAD

**Issue by cauwulixuan** [iter8-tools/iter8#1301]
**Is your feature request related to a problem? Please describe.**
For now, if I want to assess multiple versions of our ML models, by using built-in metrics, we have to launch multiple experiment.
Can we just set up only ONE experiment with multiple http urls and payloads, so that we can assess multiple models much more easily.

**Describe the solution you'd like**
Just like
```
./iter8 k launch \
--set "tasks={http,assess}" \
--set http.urls[0]=http://models1.default/post \
--set http.payloadFile[0]=file1
--set http.urls[0]=http://models2.default/post \
--set http.payloadFile[1]=file2
--set assess.SLOs.upper.http/latency-mean=50 \
--set assess.SLOs.upper.http/error-count=0 \
--set assess.SLOs.upper.http/error-rate=0 \
--set assess.SLOs.lower.http/request-count=5 \
--set runner=job
```

**Comment by cauwulixuan** [comment]
This should be a common use case, think about one scenario:
I have 2 versions of ML models, I can launch an experiment to run `http` task, moreover, if I want to use my own metrics, I can just set up `custommetrics` task in the same experiment, other than launch a new experiment. When it comes to the result, all metrics(built-in or custom metrics) can be filled in `experiment.Result`, and with all these metrics, we can decide which model is better.

**Comment by kalantar** [comment]
already done -- http/grpc tests now support multiple endpoints
