### ISSUE TITLE
Design and implement Iter8 experiment features for A/B(/n) testing

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1309]
**Is your feature request related to a problem? Please describe.**
Iter8 experiments support SLO validation with custom metrics, and performance testing (with load generation). We want a similar capability for A/B(/n) testing.

**Describe the solution you'd like**
1. An Iter8 experiment task that will fetch A/B(/n) metrics
2. Extend the assess task to work with reward metrics (this should work for metrics that are created by the A/B(/n) service as well as custom metrics)
3. Update the report so that insights like winner (that are specific to A/B(/n) testing are surfaced)

**Comment by kalantar** [comment]
no longer relevant
