### ISSUE TITLE
Templates folder in hub

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1320]
**Is your feature request related to a problem? Please describe.**
Payload template URLs used in notification tasks are based off of Alan's (@Alan-Cha) personal gist URLs.

**Describe the solution you'd like**
Create a templates folder in the [hub repo](https://github.com/iter8-tools/hub/). Put the templates under this folder, and use their URLs.

**Comment by kalantar** [comment]
This was done in `v0.12-pre`, no? Can we close this?
