### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by elgamal2020** [iter8-tools/iter8#1326]
Hello,

I have tried the binary 

./darwin-amd64/iter8 -h
-bash: ./darwin-amd64/iter8: cannot execute binary file: Exec format error

Then to make the package 

 make build
GO111MODULE=on go build  -trimpath -tags '' -ldflags '-w -s -X github.com/iter8-tools/iter8/base.Version=v0.11.11 -X github.com/iter8-tools/iter8/cmd.gitCommit=6a697aff3889517ce4281ee7399d27998006ce72' -o '/home/ubuntu/iter8/iter8/bin'/iter8 ./
go: errors parsing go.mod:
/home/ubuntu/iter8/iter8/go.mod:5: unknown block type: retract
make: *** [Makefile:50: /home/ubuntu/iter8/iter8/bin/iter8] Error 

Can it function on x86 architecture ?

Thanks a lot

**Comment by sriumcp** [comment]
Hello. Yes, it can function on x86 architecture (and for that matter, on any architecture supported by golang cross compiler).

Just to be sure, `darwin-amd64` is meant for MacOS. Did you try the Darwin binary on the MacOS? On MacOS, you can also install Iter8 using `brew` (https://iter8.tools/0.11/getting-started/install/).

**Comment by sriumcp** [comment]
What is the OS and architecture on which you are running? 
***
Based on your comment, I am guessing you are attempting to run Iter8 on `ubuntu`.

Assuming your arch is `x86-64`, the `linux-amd64` binary should work for you.
***
If you are interested in running iter8 on a 32-bit ubuntu, please let us know. We can easily release binaries for 32 bit linux as well, as part of our CI.

**Comment by kalantar** [comment]
we now use helm to install
