### ISSUE TITLE
Review exported symbols

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1329]
Are symbols (funcs, fields, methods) exported because they are part of the public API surface, or because the exports are needed for testing in other packages?
***
It is preferable to not export any symbols for the latter purpose, and do only for the former purpose. Review the code, and eliminate unwanted exports.

References:

1. https://engineering.kablamo.com.au/posts/2019/export-test
2. https://github.com/uber-go/guide/blob/master/style.md 
3. https://stackoverflow.com/questions/19998250/proper-package-naming-for-testing-with-the-go-language/31443271#31443271
4. https://jdkaplan.dev/thinkin-logs/2021-10-07/

**Comment by kalantar** [comment]
This has been done as a part of code review.
