### ISSUE TITLE
Status update in ABn service

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1333]
**Is your feature request related to a problem? Please describe.**
For `addEvent`, `deleteEvent`, and `updateEvent` -- we would like to treat these as analogous to status updates in a CRD. In particular, the application structure should be read from the cluster instead of patched (this is the recommended solution in the Kubernetes controller handbook).

For this functionality, it makes sense to pin the Kubernetes resource kind associated with an application. So while, tracks and versions can appear and disappear dynamically, the ABn service is configured ahead of time for certain applications -- and also knows the defining resource kind for each applications.

Consider Kubernetes resource cache for this purpose (for optimization reasons; cache API is already provided by Kubernetes).

A few things we want to consider as part of the above refactoring as follows:
1. Single function for add/delete/update -- that determines application state (ignoring metrics) -- this is desirable. Implementation note: generic informer also comes with a lister.
2. For lookup, can we get away with in-memory operations only -- this is desirable.
3. Keep app's track/version info purely in-memory -- this implies an HTTP API for the Iter8 experiment task to query (since app's track/version info will be purely in-memory).
4. For WriteMetric, we leverage batched writes -- write whatever is in memory.
5. Read metrics secret into memory -- whenever you get an event for an application (if you already have this in memory -- ignore).
6. Eliminate periodic flush of metrics -- in favor of in-memory with batched-writes with an API that serves application state.

**Comment by kalantar** [comment]
This was done in https://github.com/iter8-tools/iter8/pull/1313
