### ISSUE TITLE
Update charts only in `iter8 hub`

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1342]
**Is your feature request related to a problem? Please describe.**
Manually testing changes to the `iter8lib` chart (in https://github.com/iter8-tools/hub) is challenging because the launch command upgrades the chart dependencies (cf. https://github.com/iter8-tools/iter8/blob/master/action/launch.go#L120). This happens even when `--noDownload` is specified. Local changes to the dependent chart (`iter8lib`) are then ignored.

**Describe the solution you'd like**
Move the upgrade to the `hub` command. In this case, the upgrade will take place only if the charts are downloaded. When not downloaded, local dependencies will be used.

**Describe alternatives you've considered**
A workaround is to modify the dependencies in the `iter8` chart to refer to the local file system: `repository: file://../iter8lib` However, this is error prone and requires constant changing.

**Additional context**
Is it even necessary to include the upgrade in the `hub` command? Aren't we always downloading the chart and its dependencies. We should explore this. @sriumcp commented (in slack): 
> Upgrade seems necessary only because we are using the Git protocol to do the download, followed by the Helm protocol for launch. If we launch purely using Helm (without the Git based hub action), even download might be unnecessary (let alone upgrade dependency).

**Comment by kalantar** [comment]
I updated the problem description. The reference to where upgrade was happening was incorrect.

**Comment by kalantar** [comment]
It appears that the `hub` command downloads all the charts in a remote charts folder. This would include the dependency`iter8lib`. This is sufficient for now. However, it would not include any (future) dependencies on other charts not colocated with the `iter8` chart.

**Comment by sriumcp** [comment]
Even though the `hub` command downloads all the charts, the dependency may not refer to `repository: file://../iter8lib` ... it might refer to `https:// ...` (in other words, the actual Helm repo supported by the `hub`). This means you still might need to end up manually editing the dependencies.

**Comment by kalantar** [comment]
This has been addressed in `v.12.0-pre`. `iter8lib` was removed eliminating the dependency.
