### ISSUE TITLE
AutoX design requirements

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1351]
AutoX will be taking advantage of ArgoCD to install, update, and delete Helm charts.

When the config is created, a set of immutable secrets should also be created, one for each chart.

This secret will be assigned as the owner of the ArgoCD applications that will be created by the watcher. Use the UID of the secret.

This way, when the secrets are deleted, the applications will also be deleted.

**Comment by sriumcp** [comment]
1. **Kubernetes trigger object exists (i.e., the end-user application object that autox controller is configured to watch)**
* **has all the right labels** => _No ArgoCD app object in the cluster_ :: create/apply an ArgoCD app object 
2. **Existing Kubernetes trigger object (i.e., the end-user application object that autox controller is configured to watch)**
* **has all the right labels, under the covers, the version label has been changed** => _There is an ArgoCD app object in the cluster_ :: desired values (based on AutoX values computation logic) isDeepEqualTo current values (based on Argo CD app object in cluster) ? do nothing : delete argocd app object and create/apply an ArgoCD app object
3. **Existing Kubernetes trigger object (i.e., the end-user application object that autox controller is configured to watch)**
* **doesn't have all the required labels** => _There is an ArgoCD app object in the cluster_ :: delete argocd app object || delete argocd app object (ignore app doesn't exist error)
4. **Trigger object doesn't exist** => Reuse the action logic in 3.

**Comment by kalantar** [comment]
autox feature delivered. any other design issues should be opened as new issues.
