### ISSUE TITLE
Iter8 assert behavior with timeout

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1354]
**Is your feature request related to a problem? Please describe.**
`iter8 assert` and `iter8 k assert` accept a timeout parameter. Currently, this timeout is enforced even if the experiment is completed (and other conditions such as SLOs are yet to be satisfied). 

**Describe the solution you'd like**
Stop and return from the assert command if one of the following happens:
1. Timeout is exceeded.
2. Assert conditions are satisfied.
3. Experiment is complete.

**Comment by kalantar** [comment]
no longer relevant; `iter8 assert` no longer supported
