### ISSUE TITLE
Support multiple end points in http and grpc load test tasks

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1364]
**Is your feature request related to a problem? Please describe.**
Current `http` and `grpc` tasks support load testing a single http and grpc endpoint respectively. We want to support testing of multiple endpoints.

**Design:**

1. Load test multiple endpoints; they may share some configuration.

```shell
iter8 k launch \
--set "tasks={ready,http,assess}" \
--set ready.deploy=httpbin \
--set ready.service=httpbin \
--set ready.timeout=60s \
--set http.numRequests=200 \
--set http.endpoints.getit.url=http://httpbin.default/get \
--set http.endpoints.postit.url=http://httpbin.default/post \
--set http.endpoints.postit.payloadStr=hello \
--set assess.SLOs.upper.http/getit/latency-mean=50 \
--set assess.SLOs.upper.http/getit/error-count=0 \
--set assess.SLOs.upper.http/postit/latency-mean=150 \
--set assess.SLOs.upper.http/postit/error-count=0 \
--set runner=job
```

2. Load test multiple grpc endpoints; they may share some configuration.

```shell
iter8 k launch \
--set "tasks={grpc,assess}" \
--set grpc.host="hello.default:50051" \
--set grpc.endpoints.hello.call="helloworld.Greeter.SayHello" \
--set grpc.endpoints.goodbye.call="helloworld.Greeter.SayGoodBye" \
--set grpc.protoURL="https://raw.githubusercontent.com/grpc/grpc-go/master/examples/helloworld/helloworld/helloworld.proto" \
--set assess.SLOs.upper.grpc/hello/error-rate=0 \
--set assess.SLOs.upper.grpc/goodbye/latency/p'97\.5'=800 \
--set runner=job
```

**Comment by kalantar** [comment]
How should shared configuration be interpreted? In the HTTP example, does `--set http.numRequests=200` mean 200 total requests? Or 200 per endpoint?

What does it look like if I want to test against a single endpoint? Do I need to include the endpoints label?  In part this is a question about which configuration can be shared and which cannot.

**Comment by sriumcp** [comment]
Good questions!  Here's my take... 

1. The tasks continue to behave as it does today -- i.e., if you do not have endpoints, then you get exactly the behavior you get today.
2. If the tasks do have endpoint specification, then the final config of each endpoint = shared spec merged with endpoint spec. If fields are repeated across shared and endpoint specs, the latter takes precedence.
3. Anything field of the spec can be shared (i.e., any field is syntactically valid for sharing). In practice, we expect that users will find it more useful to share certain fields (for e.g., numRequests, this is the number of requests used for *each* endpoint load gen process) than others (e.g., URLs, which might have distinct values for different endpoints).

**Comment by sriumcp** [comment]
As an extension, we may want to introduce `glob` patterns or wild cards for SLOs. E.g., 

```yaml
--set assess.SLOs.upper.http/*/latency-mean=50
```

**Comment by kalantar** [comment]
Completed with PRs: 
iter8: https://github.com/iter8-tools/iter8/pull/1409
hub: https://github.com/iter8-tools/hub/pull/54 and https://github.com/iter8-tools/hub/pull/59
doc: https://github.com/iter8-tools/docs/pull/64
