### ISSUE TITLE
Remove local experiments

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1370]
Iter8 has a primary use-case, that of running experiments inside Kubernetes.

Local experiments were a nice way for the Iter8 development to get started, and it was especially useful in fleshing out the task framework. But it has now outlived its purpose since Kubernetes experimentation have arrived in a full fledged manner in Iter8. AFAIK, no one has posed a question about local experiments in all of our community interactions, let alone express an interest in using the feature!

Besides, the combination of `iter8 k launch --set runner=none` along with `iter8 k run` can be used to run an experiment on your local machine (for debugging purposes only, by Iter8 experiment authors).

So, remove local experiments and document the above combination for debugging purposes.

***

Side effect: we will no longer have `iter8 k` subcommand. Things like `iter8 k launch` will end up as `iter8 launch` and will refer to Kubernetes experiments. Among other things, this offers a significant simplification of the CLI.

***

Side effect: This should also enable us to have a cleaner positioning of Iter8 as a Kubernetes app testing toolbox.

**Comment by kalantar** [comment]
local experiments removed. Another issue created to remove `iter8 k` subcommand. (https://github.com/iter8-tools/iter8/issues/1492).
