### ISSUE TITLE
Support sending metadata in grpc task

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1405]
**Is your feature request related to a problem? Please describe.**
In addition to the message, (meta)data can be passed to a grpc endpoint via headers in the request. In grpcurl, this is expressed using the `-H option`. 

Iter8's [grpc task](https://iter8.tools/0.13/user-guide/tasks/grpc/) should also support sending metadata as well. 

**Describe the solution you'd like**
The grpc task is implemented using [ghz](https://github.com/bojand/ghz).  It supports the following options:
```
 -m, --metadata=                Request metadata as stringified JSON.
 -M, --metadata-file=           File path for call metadata JSON file. Examples: /home/user/metadata.json or ./metadata.json.
```

**Comment by sriumcp** [comment]
Currently, there are two ways to do this in the `gRPC` task.

1. Use a `metadataURL`. For instance, the URL can respond with the JSON metadata. This is already documented in the task description.
2. The task description also says that any field in the `Config` struct of ghz can be used as input to the task. This means, today, we can do ...
```yaml
--set grpc.metadata.x=y --set grpc.metadata.a=b
```
which would lead to the following metadata being passed:
```json
{
"a": "b",
"x": "y"
}
```

***

Perhaps the documentation is not clear and must be improved in some way? If so, how?

**Comment by sriumcp** [comment]
Incidentally, I just noticed the following docs bug ...

> In the [usage example](https://iter8.tools/0.13/#usage-example), the parameters host and call correspond to the Call and Host fields respectively in the Config struct.

They should be the other way around.

**Comment by kalantar** [comment]
I was just rereading the doc and was about to close this issue :).  Let's ask that the required change be made as part of PR https://github.com/iter8-tools/docs/pull/64
