### ISSUE TITLE
Explore A/B/n with rewards

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1414]
Introduce reward  and winner to ABn experiments.

**Use Case**
Assume that metrics are generated by application and written to metrics service such as Prometheus.

*Scenario*
1. Deploy two versions of an application/ML model
2. Run Iter8 experiment specifying reward metrics
3. After each loop, report winner based on reward metrics

*Comments*
- Can also specify SLOs to validate
- A reward metric can also be used to specify an SLO
- Initially report winner for each reward metric separately; ie, not "combined" winner

**Example**
Deploy 2 ML models, for example as in this [canary experiment tutorial](https://github.com/sriumcp/kserve/blob/iter8/docs/samples/canary-testing/README.md).

Run an experiment:
```shell
iter8 k launch \
--set "tasks={ready,custommetrics,assess}" \
--set ready.isvc=${ISVC} \
--set ready.timeout=600s \
--set custommetrics.templates.kserve-prometheus="http://kserve-prometheus.tpl" \
--set custommetrics.values.labels.service_name=${ISVC}-predictor-default \
--set "custommetrics.versionValues[0].labels.revision_name=${CURRENT_REVISION}" \
--set "custommetrics.versionValues[1].labels.revision_name=${CANARY_REVISION}" \
--set "custommetrics.values.latencyPercentiles={50,75,90,95}" \
--set "assess.rewards.greater={kserve-prometheus/conversion-rate,kserve-prometheus/profit}" \
--set assess.SLOs.lower.kserve-prometheus/conversion-rate=.35 \
--set assess.SLOs.upper.kserve-prometheus/latency-mean=50 \
--set assess.SLOs.upper.kserve-prometheus/latency-p90=75 \
--set assess.SLOs.upper.kserve-prometheus/error-count=0 \
--set runner=cronjob \
--set cronjobSchedule="*/1 * * * *"
```

`iter8 k report` should be modified to include information about reward metrics/winners. Perhaps like this:

```
Experiment summary:
*******************

Experiment completed: true
No task failures: true
Total number of tasks: 1
Number of completed tasks: 1
Number of completed loops: 3

Reward evaluation:
*****************

Reward          | winner |
------          | ------ |
conversion-rate | backend-candidate-1 (v2)
profit          | insufficient data

Whether or not service level objectives (SLOs) are satisfied:
*************************************************************

  SLO Conditions                             | backend (v1) | backend-candidate-1 (v2)
  --------------                             | ---------    | ---------
  http/error-count <= 0                      | true         | true
  http/latency-mean (msec) <= 50             | true         | true 
  kserve-prometheus/latency-p90 (msec) <= 75 | true         | true
  kserve-prometheus/conversion-rate (%)      | true         | false

Latest observed values for metrics:
***********************************

Metric                   | backend (v1) | backend-candidate-1 (v2)
-------                  | -----        | -----
abn/sample_metric/count  | 35.00        | 28.00
abn/sample_metric/max    | 99.00        | 100.00
abn/sample_metric/mean   | 56.31        | 52.79
abn/sample_metric/min    | 0.00         | 1.00
abn/sample_metric/stddev | 28.52        | 31.91
```

**Comment by kalantar** [comment]
Work items:
- [x] Changes to iter8 chart
- [x] Modify custommetrics task to also record reward metrics in `Experiment.Result.Insights` ?  *not needed*
- [x] Changes to `Experiment.Result.Insights` ?  *done*
- [x] Changes to assess task
- [x] Changes to text report
- [x] Changes to html report
- [x] Tutorial: KServe, mockoon to mock metrics service

**Comment by sriumcp** [comment]
It's looking great. Perhaps instead of `greater` or `lesser`, we can make it `max` and `min`? Saves a few characters while typing but maybe conveys the same meaning?

```shell
--set assess.rewards.max.kserve-prometheus/conversion-rate \
--set assess.rewards.max.kserve-prometheus/profit \
--set assess.rewards.max.kserve-prometheus/accuracy \
--set assess.rewards.min.kserve-prometheus/expenses
```

**Comment by Alan-Cha** [comment]
Helm does not allow parameters to be set like this:

```
--set assess.rewards.max.kserve-prometheus/conversion-rate \
```

The parameter must be in the form of a key value pair.

I will suggest doing the following:

```
--set "assess.rewards.max={kserve-prometheus/conversion-rate,kserve-prometheus/profit,kserve-prometheus/accuracy}" \
```

**Comment by kalantar** [comment]
Image from "Latest observed values for metrics":

<img width="312" alt="image" src="https://github.com/iter8-tools/iter8/assets/4826865/68d17892-0adf-4909-aa47-e302cc6cf018">
