### ISSUE TITLE
lint Kubernetes manifests generated from helm charts

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1425]
Implement a workflow to "lint" Kubernetes manifests. Possible open source tools include _kubelinter_ and _kubescape_.

**Comment by Alan-Cha** [comment]
See iter8-tools/hub#60

**Comment by kalantar** [comment]
Should include all hub charts including the controller chart (WIP, issue https://github.com/iter8-tools/iter8/issues/1419)

**Comment by kalantar** [comment]
completed with PR https://github.com/iter8-tools/hub/pull/60
