### ISSUE TITLE
Enable Iter8 traffic controller with proper behavior

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1427]
**Is your feature request related to a problem? Please describe.**
Namespace scoping of Iter8 traffic controller is currently not well-defined.

**Describe the solution you'd like**
- [x] Iter8 installation should be either cluster-scoped or namespace-scoped based on its configuration.
- [x] When Iter8 install is cluster-scoped, the controller should expect variant resources to be in any namespace.
- [x] When Iter8 install is namespace-scoped, the controller should expect subjects and variant resource to all be in its own namespace.
- [x] Normalize weights correctly, even when all variants are unavailable.
- [ ] Emit controller events
 
**Describe alternatives you've considered**
Support only cluster-scope and not namespace-scope. The reason we want to do both is that we already see development environments with only namespace-scoped privileges for developers. Namespace-scoped install would speed up local development for these developers, and also possibly integrations with ecosystem tools like ODH.

**Comment by Alan-Cha** [comment]
Possible controller events:

```
Reading controller config

Validating controller config

Extracting Routemap from config

Validating RouteMap

Creating app informer for resource %s

Starting app informers factory

Creating Routemap informer

Starting Routemap informer factory

Adding Iter8 finalizer for resource %s

Removing Iter8 finalizer for resource %s

Normalizing weights for variants

Changing weights
```

Please let me know what you think. Is this what you expected? Any other events I should add?

**Comment by sriumcp** [comment]
This is a good list... perhaps we can start with the following subset?

- [ ] Failed to start app informers (event in pod namespace)
- [ ] Failed to start Routemap informer (event in pod namespace)
- [ ] ~Each type of informer event (add, update, and delete of app resources as well as routemaps) (event in routemap namespace)~
- [ ] ~Each type of informer event (add, update, and delete of app resources as well as routemaps) (event in routemap namespace)~
- [ ] Added Iter8 finalizer for resource (event in routemap namespace) (object is resource)
- [ ] Removed Iter8 finalizer for resource (event in routemap namespace) (object is resource)
- [ ] Applied template (which changes weights) (event in routemap namespace) (object is configmap)

**Comment by kalantar** [comment]
Created https://github.com/iter8-tools/iter8/issues/1434 for last remaining item (events). Closing this issue.
