### ISSUE TITLE
Find reasonable values for resource request and limit values in Helm templates

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1430]
The [Helm linter](https://docs.kubelinter.io) recommends us to set request and limit (CPU and memory) values for the Helm templates.

What should these values be?

**Comment by Alan-Cha** [comment]
Related to iter8-tools/hub#60

**Comment by kalantar** [comment]
prerequisite for https://github.com/iter8-tools/iter8/issues/1425

**Comment by kalantar** [comment]
values committed as part of linter changes.
