### ISSUE TITLE
Create proposal for incubation under Open Data Hub

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1435]
Create a proposal for Iter8 incubation in the [Open Data Hub (ODH)](https://opendatahub.io/). 
See also https://github.com/opendatahub-io

**Comment by sriumcp** [comment]
1. Sample proposals are [here](https://github.com/sriumcp/opendatahub-community/tree/main/proposal).
2. We need to create an Iter8 proposal along the lines of code flare (distributed workloads) proposal; also try to absorb the best of all the other proposals.
3. As part of 2, we need to clean up Iter8 documentation, starting with what is Iter8, how to install it, and its architecture.
4. As part of 2, clarify how ODH users will install Iter8. How is `kustomize` based install supposed to help ODH users?
5. Clarify how Iter8 amplifies service mesh/Istio value.

**Comment by kalantar** [comment]
Draft proposal here: https://github.com/opendatahub-io/opendatahub-community/pull/39

**Comment by kalantar** [comment]
done
