### ISSUE TITLE
Possibility to call multiple http URLs during test

### ISSUE THREAD

**Issue by mertdotcc** [iter8-tools/iter8#1450]
I am using the following `iter8` command to test one of my Camel-K integrations:

```
iter8 k launch \
--set "tasks={ready,http,assess}" \
--set ready.ksvc=customer-integration-mock \
--set http.url=http://customer-integration-mock.default.knative.test.com/customer/1 \
--set http.numRequests=100000 \
--set http.connections=250 \
--set http.qps=500 \
--set assess.SLOs.upper.http/latency-mean=200 \
--set assess.SLOs.upper.http/error-count=0 \
--set runner=job
```

which works perfectly fine and does what's needed.

I was wondering whether it would be possible to have multiple `http.url` descriptions here so that I can test not just one but multiple endpoints within my integration. The idea is, I would have a configuration that consists of multiple `http.url`s and `iter8` would portion whatever I set `http.numRequests` to the number of URLs that I have. 

So a configuration like this would be possible:
```
iter8 k launch \
--set "tasks={ready,http,assess}" \
--set ready.ksvc=customer-integration-mock \
--set http.url=http://customer-integration-mock.default.knative.test.com/customer/1 \ @GET@
--set http.url=http://customer-integration-mock.default.knative.test.com/customer \   @POST@
--set http.numRequests=100000 \
--set http.connections=250 \
--set http.qps=500 \
--set assess.SLOs.upper.http/latency-mean=200 \
--set assess.SLOs.upper.http/error-count=0 \
--set runner=job
```

I am not sure whether this is already possible so I am just shooting my question here. 🙂

Many thanks in advance!

**Comment by kalantar** [comment]
Please see https://iter8.tools/0.13/tutorials/load-test-http-multiple/. Does this meet your needs?

**Comment by mertdotcc** [comment]
It exactly does, thanks! Must've missed it.
