### ISSUE TITLE
Merge `hub` repo into `iter8` repo

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1457]
Excerpt from #1448:

Merge `hub` repo into `iter8` repo. This way, we will still have a `helm` repo for installing Iter8 helm charts (and not a Git repo). However, we will not have two repos, only one. So, `iter8` will become a mono repo, containing both `Go` code, and `Helm` charts.

**Comment by kalantar** [comment]
The version of hub that was merged was an old version. `charts/traffic-templates` is missing.  Perhaps also some changes to `traffic`.

**Comment by kalantar** [comment]
Also need to replace references to hub repo in:
- `charts/iter8/Chart.yaml`
- `charts/iter8/templates/_task-github.tpl`
- `charts/iter8/templates/_task-slack.tpl`
