### ISSUE TITLE
Using iter8 action fails because the Dockerfile references the wrong GitHub release URL

### ISSUE THREAD

**Issue by chgl** [iter8-tools/iter8#1488]
**Describe the bug**

Building the container image via the Dockerfile fails with `tar: This does not look like a tar archive`. For example, this happens when using this repo as an action in a GitHub workflow.

This happens because release v0.14.0 does not include any binaries as part of the release (https://github.com/iter8-tools/iter8/releases/tag/v0.14.0), but the Dockerfile https://github.com/iter8-tools/iter8/blob/master/Dockerfile#L12 attempts to download the binary anyways.

**To Reproduce**
Run `docker build .` in the root of this repository.

**Expected behavior**
The container should build successfully.

**Screenshots**

<img width="1327" alt="image" src="https://github.com/iter8-tools/iter8/assets/5307555/7144cda0-a14a-4c27-876c-94cc7c366ac8">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Output of the `iter8 version` command

**Additional context**

**Comment by sriumcp** [comment]
This is a good catch. For end-users installing the Iter8 CLI, we have already moved away binary installs, to a pure go based install. 

The Dockerfile should do the same. For e.g., we can have a two stage build, where the 1st stage involves go build, and the second stage involves moving the `iter8` to a minimal image.
