### ISSUE TITLE
Create getting started documentation for traffic control

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1491]
There is a getting started documentation for experiments. Similarly, we need a getting started documentation for traffic control.

As part of this exercise, clean up concepts, and install.

**Comment by kalantar** [comment]
This should cover https://github.com/iter8-tools/iter8/issues/1443

**Comment by sriumcp** [comment]
## Substance

1. We want to document naming conventions (with a suffix -0, -1, etc.), for e.g., in topics.
2. We say that any name can be specified for resources. How? Should be documented in topics.
3. Virtual services created by the traffic controller always need to return the version number from where the responses are coming from.
4. Traffic templates describe
```
targetEnv: kserve-modelmesh
trafficStrategy: blue-green
```
Explanation are needed (in topics) for exactly what these are. In fact, a schema and allowable set of values is needed for traffic-template chart. This is documented today in `values.yaml` file. We want it also under topics.
5. Helm chart needs to support a new `targetEnv`.

## Style

1. We want the table of contents for this tutorial to be a few simple steps.
2. We need be consistent about version number. Perhaps, 0-indexed, v0, v1, are the way to go (considering that's how weight specification works today; there's a weights list accessible within the routemap, and this is zero-indexed). So, v0 always be aliased as "primary", `v1` can always be aliased as `candidate`, and `vn` can always be aliased as `Version n`.
3. Consider using the term `version number` (0, 1, 2, ....); use version number in the doc file.
4. In our tutorials, we disambiguate different version resources using this label `app.kubernetes.io/version`. Consider not using `v<number>` for this label. Consider using a hash value, e.g., `28a3g` as a way to disambiguate (no `v` prefix).

**Comment by kalantar** [comment]
done in v0.15 documentation
