### ISSUE TITLE
Is `NumUsers` redundant? 

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1519]
`NumUsers` in `VersionMetricSummary` (see [here](https://github.com/iter8-tools/iter8/blob/6a9bde9dbc700a4a58d15cb2301f7aef4def19dc/controllers/storageclient/interface.go#L24)) exists along side of `Count` in `SummaryOverUsers` and `SummaryOverTransactions` (see [here](https://github.com/iter8-tools/iter8/blob/6a9bde9dbc700a4a58d15cb2301f7aef4def19dc/controllers/storageclient/interface.go#L6))

My original impressions was that `NumUsers` may be different from `Count`. However, if we intended to add 0s for metrics over users for users that did not set any metrics (`lookup()`), then the `Count` for `SummaryOverUsers` should always equal `NumUsers`.

If that is the case, then `NumUsers` may be redundant and could be removed.

**Comment by kalantar** [comment]
addressed by other changes
