### ISSUE TITLE
Document Grafana dashboard usage

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1521]

**Comment by kalantar** [comment]
This should include how to install and configure the dashboard.

**Comment by Alan-Cha** [comment]
First draft: https://gist.github.com/Alan-Cha/d82bb0124d50ae3d7a142dec992a7924

**Comment by kalantar** [comment]
The documentation will be incorporated into the tutorials. See https://github.com/iter8-tools/iter8/issues/1513
