### ISSUE TITLE
Set the refresh rate in the Iter8 grafana dashboard

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1532]
Currently the Iter8 dashboard does not set a refresh rate. The user must explicitly refresh the data or set the rate themselves. Can we set it to a reasonable default (30s).

**Comment by Alan-Cha** [comment]
Done, see [here](https://gist.githubusercontent.com/Alan-Cha/aa4ba259cc4631aafe9b43500502c60f/raw/034249f24e2c524ee4e326e860c06149ae7b2677/gistfile1.txt)

The `refresh` in the Grafana config can just be set to the desired refresh rate.
