### ISSUE TITLE
Removal of old tutorials using `custommetrics`

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1569]
The following tutorials depend on the `custommetrics` which will be removed in v0.16

Is it possible to adapt these tutorials to work without `custommetrics`? Or do they need to be removed?

- [ ] [kserve canary testing](https://iter8.tools/0.15/tutorials/integrations/kserve/canary-testing/#launch-iter8-experiment)
- [ ] [kserve continuous validation](https://iter8.tools/0.15/tutorials/integrations/kserve/continuous-validation/#launch-iter8-experiment)

**Comment by kalantar** [comment]
This is similar to https://github.com/iter8-tools/iter8/issues/1570.

**Comment by Alan-Cha** [comment]
kserve canary testing -> has been replaced by Michael already
kserve continuous testing -> remove
