### ISSUE TITLE
Removal of old tutorials

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1570]
The v0.15 documentation contains references to many old tutorials, for example from v0.7. Which the upcoming v0.16 documentation, should we consider removing these old tutorials or properly integrating them with v0.16?

Should these old tutorials be removed or properly adopted in v0.16.

Links to previous versions in current docs
- [ ] [Istio examples](https://iter8.tools/0.15/tutorials/integrations/kserve/continuous-validation/#launch-iter8-experiment)
  - [ ] [Hybrid (A/B + SLOs) testing](https://iter8-tools.github.io/iter8/0.7/tutorials/istio/quick-start/)
  - [ ] [SLO validation](https://iter8-tools.github.io/iter8/0.7/tutorials/istio/testing-strategies/slovalidation/)
  - [ ] [SLO validation (single version)](https://iter8-tools.github.io/iter8/0.7/tutorials/istio/testing-strategies/conformance/)
  - [ ] [Progressive traffic shifting](https://iter8-tools.github.io/iter8/0.7/tutorials/istio/rollout-strategies/progressive/)
  - [ ] [Fixed % split](https://iter8-tools.github.io/iter8/0.7/tutorials/istio/rollout-strategies/fixed-split/)
- [ ] [kserve examples](https://iter8.tools/0.15/tutorials/integrations/kserve/kserve/)
  - [ ] [A/B Testing and Progressive Traffic Shift](https://iter8-tools.github.io/iter8/0.7/tutorials/kfserving/quick-start/)
  - [ ] [Hybrid (A/B + SLOs) testing](https://iter8-tools.github.io/iter8/0.7/tutorials/kfserving/testing-strategies/hybrid/)
  - [ ] [Progressive traffic shifting](https://iter8-tools.github.io/iter8/0.7/tutorials/kfserving/rollout-strategies/progressive/)
  - [ ] [Fixed-%-split](https://iter8-tools.github.io/iter8/0.7/tutorials/kfserving/rollout-strategies/fixed-split/)
  - [ ] [Session affinity](https://iter8-tools.github.io/iter8/0.7/tutorials/kfserving/rollout-strategies/session-affinity/)
- [ ] [seldon examples](https://iter8.tools/0.15/tutorials/integrations/seldon/)
  - [ ] [Hybrid (A/B + SLOs) testing](https://iter8-tools.github.io/iter8/0.7/tutorials/seldon/quick-start/)
  - [ ] [Progressive traffic shifting](https://iter8-tools.github.io/iter8/0.7/tutorials/seldon/rollout-strategies/progressive/)
- [ ] [linkerd a/b](https://iter8.tools/0.15/tutorials/integrations/linkerd/)
- [ ] Docs for Iter8 v0.8
- [ ] Docs for Iter8 v0.7

Link to external blog
- [ ] [knative http and grpc](https://knative.dev/blog/articles/performance-test-with-slos/)

**Comment by kalantar** [comment]
@sriumcp any thoughts on this?

**Comment by Alan-Cha** [comment]
I am in the opinion of removing this old tutorials. A lot of them seem to be incompatible (for example, requiring `assess`). In the very least, they need to be rewritten and tested for v0.16

**Comment by Alan-Cha** [comment]
Links to previous versions in current docs
- [ ] [Istio examples](https://iter8.tools/0.15/tutorials/integrations/kserve/continuous-validation/#launch-iter8-experiment) (remove and just say see examples)
  - [ ] [Hybrid (A/B + SLOs) testing](https://iter8-tools.github.io/iter8/0.7/tutorials/istio/quick-start/)
  - [ ] [SLO validation](https://iter8-tools.github.io/iter8/0.7/tutorials/istio/testing-strategies/slovalidation/)
  - [ ] [SLO validation (single version)](https://iter8-tools.github.io/iter8/0.7/tutorials/istio/testing-strategies/conformance/)
  - [ ] [Progressive traffic shifting](https://iter8-tools.github.io/iter8/0.7/tutorials/istio/rollout-strategies/progressive/)
  - [ ] [Fixed % split](https://iter8-tools.github.io/iter8/0.7/tutorials/istio/rollout-strategies/fixed-split/)
- [ ] [kserve examples](https://iter8.tools/0.15/tutorials/integrations/kserve/kserve/) (have been updated)
  - [ ] [A/B Testing and Progressive Traffic Shift](https://iter8-tools.github.io/iter8/0.7/tutorials/kfserving/quick-start/)
  - [ ] [Hybrid (A/B + SLOs) testing](https://iter8-tools.github.io/iter8/0.7/tutorials/kfserving/testing-strategies/hybrid/)
  - [ ] [Progressive traffic shifting](https://iter8-tools.github.io/iter8/0.7/tutorials/kfserving/rollout-strategies/progressive/)
  - [ ] [Fixed-%-split](https://iter8-tools.github.io/iter8/0.7/tutorials/kfserving/rollout-strategies/fixed-split/)
  - [ ] [Session affinity](https://iter8-tools.github.io/iter8/0.7/tutorials/kfserving/rollout-strategies/session-affinity/)
- [ ] [seldon examples](https://iter8.tools/0.15/tutorials/integrations/seldon/) (leave as is for now)
  - [ ] [Hybrid (A/B + SLOs) testing](https://iter8-tools.github.io/iter8/0.7/tutorials/seldon/quick-start/)
  - [ ] [Progressive traffic shifting](https://iter8-tools.github.io/iter8/0.7/tutorials/seldon/rollout-strategies/progressive/)
- [ ] [linkerd a/b](https://iter8.tools/0.15/tutorials/integrations/linkerd/) (remove)
- [ ] Docs for Iter8 v0.8 (remove)
- [ ] Docs for Iter8 v0.7 (remove)
- [ ] Litmus examples (remove chaos tutorial from the tutorials but keep link to v0.15 tutorial in integrations)

**Comment by kalantar** [comment]
done in v0.16
