### ISSUE TITLE
`http` and `grpc` tasks send data at the end of the task, not end of experiment

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1575]
Because the `http` and `grpc` tasks send data at the end of the task, not end of experiment, some of the experiment summary may be in correct.

Experiment status (success/failure) shows success/failure at the time of the task, not at the end of the experiment
Completed tasks shows the num of complete tasks at the time of the task, not at the end of the experiment

**Comment by kalantar** [comment]
done in v0.16
