### ISSUE TITLE
Outdated experiment result in Grafana

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1580]
The Grafana dashboard should display the up to date experiment result. 

This means that the current method of sending the data for the Grafana dashboard in one go at the end of the task will not work. We can, as one solution, save the experiment result and the rest of the data separately in the metrics store. The experiment result will be stored at the end of each task whereas the rest of the data will be stored at the end of the related task.

**Comment by kalantar** [comment]
Fixed in PR https://github.com/iter8-tools/iter8/pull/1585
