### ISSUE TITLE
Remove Revision number

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1583]
Should [Revision](https://github.com/iter8-tools/iter8/blob/d1e9ed53263ac9debbdb90a149844b22fbb3e9d4/base/experiment.go#L52) be removed from Experiment?

What are the implications of removing this? What do we want the expected behavior of rerunning experiments going forward?

**Comment by Alan-Cha** [comment]
We will keep it in for now. It is a benign feature and will require more cycles.

**Comment by kalantar** [comment]
Even with move to `helm upgrade` we still have revisions.

**Comment by sriumcp** [comment]
Revision number ensures that the old job spec is deleted and a new job spec is created whenever an experiment is upgraded. Without the revision number, `helm` will not recreate a job, so `helm upgrade` will not result in a new experiment run.
