### ISSUE TITLE
Clean up makefile after dockerfile changes 

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1606]
With #1605, we added a new dockerfile and removed the old one. Additionally, there are some commands in the makefile that are obsolete, for example `dist`. We should remove these. In addition, we will also need to update instructions in the `CONTRIBUTING.md` to describe how a user can locally build the Iter8 image and push to Docker.

**Comment by kalantar** [comment]
directory `_dist` and all references to it can be eliminated (also from .gitignore)

**Comment by kalantar** [comment]
Instructions in `CONTRIBUTING.md` already updated.

**Comment by kalantar** [comment]
Fixed by https://github.com/iter8-tools/iter8/pull/1621
