### ISSUE TITLE
Replace iter8.tools/group label

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1624]
We add label `iter8.tools/group` to the job/pod running an experiment. Can we use another label (a helm label) or `iter8.tools/name` label instead.

This is publicly visible in our replacement to `iter8 k log`: `kubectl logs -l iter8.tools/group=foo`

**Comment by kalantar** [comment]
We should determine what else the label is used for.

**Comment by sriumcp** [comment]
We can simply use the `helm` recommended label.

https://helm.sh/docs/chart_best_practices/labels/

`app.kubernetes.io/instance` is what Helm recommends for release names (a.k.a. experiment groups).

**Comment by kalantar** [comment]
The user sees the "group" name in two places. One is in the configuration of the Grafana data source (where we currently use the parameter name "experiment") and the other is to get logs (where it is called "iter8.tools/group"). 

We want to make the label more consistent. In practice it is a helm release name. In concept it is the name of the test.  We are planning to change the Grafana parameter to "test" and I suggest we use the same for logs ... "iter8.tools/test"

This terminology is more consistent.  I don't think our documentation uses any term for this concept. It is just present as a label in the helm commands without explanation.

**Comment by kalantar** [comment]
fixed in v0.17
