### ISSUE TITLE
 Does iter8 still support custom metric now?

### ISSUE THREAD

**Issue by ZiShuSong** [iter8-tools/iter8#1666]
**Is your feature request related to a problem? Please describe.**

Does iter8v1.1 still support custom metric?I did not find documentation from the user-guide since version v0.15。How do I create custom metric?

**Comment by kalantar** [comment]
The support for the built in custom metric action (assess) has been removed from Iter8. Instead, Iter8 has exposed, via a REST API, the raw metrics data allowing you to compute whatever functions you desire. You should also be able to implement these in Grafana allowing you to visualize them as well (would require dashboard changes)

To access the metric data, first expose the iter8 service:
```shell
kubectl port-forward svc/iter8 8080:8080
```

Then, for HTTP tests:
```
http://localhost:8080/httpDashboard?namespace=<namespace>&test=<name>
```
and for gRPC tests:
```
http://localhost:8080/grcpDashboard?namespace=<namespace>&test=<name>
```
