### ISSUE TITLE
Preliminary modification to Grafana

### ISSUE THREAD

**Issue by sushmarchandran** [iter8-tools/iter8#206]
Sample (modified) Graphing URL:
`http://localhost:3000/d/eXPEaNnZz/iter8-application-metrics?var-kind=deployment&var-namespace=bookinfo-iter8&var-baseline=reviews-v3&var-candidate=reviews-v5&var-pod_field=pod&from=1576820317351&to=1576820377696`

New variables:
1. var-kind: takes the value: `service` or `deployment` - indicates the kind of experiment being conducted, i.e with services or with deployments
2. var-pod_field: takes the value: `pod` or `pod_name` - indicates the version of experiment being used, i.e `pod` for vk8 >= 1.16 and `pod_name` for vk8 < 1.16

Removed variables:
1. var-service

**Comment by sriumcp** [comment]
Done.
