### ISSUE TITLE
Modifications for OpenShift support

### ISSUE THREAD

**Issue by a-roberts** [iter8-tools/iter8#21]
Hi all, I've been looking into using Iter8 on OpenShift and noticed a few issues we could address for all to benefit from really

1) **containers running as root**, I had to do `oc adm policy add-scc-to-user anyuid -z default -n iter8`, an `iter8` user would be great (so a Dockerfile change required is my guess)

2) **cpu/memory limits should be increased** for analytics-iter8 (I personally went with 1000 just to get things running OK)

- I expect https://raw.githubusercontent.com/iter8-tools/iter8-analytics/master/install/kubernetes/iter8-analytics.yaml needs to specify larger than usual cpu/memory limits, perhaps 256 will do for both

3) **have to roll out one's own Prometheus as the one in OpenShift out of the box is meant for monitoring itself and not user applications and indeed modify the backend URL**. 

To this end, it'd be useful to have some known supported example and suggesting what the endpoint would be and a little on debugging, based on the iter8 code it looks like we're using /api/v1 and that has to be reachable. I personally never got this part working on OpenShift (always getting an invalid char at column 4 error, or connection refused)

**Comment by kalantar** [comment]
We've dealt with all of these. See https://github.com/iter8-tools/docs/blob/v0.1.1/doc_files/platforms/redhat_openshift.md for install directions.
