### ISSUE TITLE
Traffic percentage for candidates are not complete

### ISSUE THREAD

**Issue by kimikowang** [iter8-tools/iter8#247]
```
NAME              PHASE       STATUS                                              ITERATION   BASELINE     PERCENTAGE   CANDIDATES                PERCENTAGE
rolltowinner      Completed   ExperimentCompleted: Last Iteration Was Completed   2           reviews-v1   20           [reviews-v2 reviews-v3]   80
```

**Comment by kalantar** [comment]
@sriumcp @sushmarchandran @kimikowang @fabolive I've implemented this without traffic split for candidates. Rather, we capture the current winner and probability they are selected as a final winner. Any thoughts?

```bash
NAME                   PHASE       STATUS                                              BASELINE         PERCENTAGE   CANDIDATES
    CURRENT BEST     CONFIDENCE
productpage-abn-test   Completed   ExperimentCompleted: Last Iteration Was Completed   productpage-v1   2            [productpage-v2 productpage-v3
]   productpage-v3   0.9989
```

**Comment by sriumcp** [comment]
I didn't understand what "Traffic percentage for candidates are not complete" means. Are you saying they are not adding up 100% -- in which case we have a bug.

**Comment by sriumcp** [comment]
Perhaps we should print something like:  `productpage-v1 (2%) productpage-v2 (1%) productpage-v3 (97%)` and call them `Traffic to Baseline` and `Traffic to Candidates` respectively?

**Comment by kalantar** [comment]
> I didn't understand what "Traffic percentage for candidates are not complete" means. Are you saying they are not adding up 100% -- in which case we have a bug.

If you recall, the candidate percentages weren't showing at all. This is what the issue title means.

**Comment by sriumcp** [comment]
Ok. Could we please have them show up as above: i.e., `productpage-v1 (2%)` under baseline and  `productpage-v2 (1%) productpage-v3 (97%) under candidates?

**Comment by kalantar** [comment]
Discussion 7/23 (including @fabolive @kimikowang @kalantar @sriumcp) decided on these columns:

`NAME  HOST         PHASE       WINNER FOUND   CURRENT BEST  STATUS                EXPERIMENT TYPE`

we explored what they might look like for different test types: 

```bash
performance test
name, productpage, waiting,     -,      test version, missing version               performance (0 candidates)
name, productpage, in progress, -,      test version, iteration 8                   performance
name, productpage, completed,   -,      test version, traffic to baseline/winner    performance

canary test
name, productpage, waiting,     no,     -,            missing candidates            canary (exactly 1 candidate., no reward)
name, productpage, in progress, no/yes, v2,           iteration                     canary
name, productpage, completed,   yes,    v3,           traffic to baseline/winner    canary

a/b test
name, productpage, waiting,     no,     -,            missing candidates            a/b (exactly 1 candidate. reward)
name, productpage, in progress, no/yes, v2,           iteration                     a/b
name, productpage, completed,   yes,    v3,           traffic to baseline/winner    a/b

a/b/n test
name, productpage, waiting,     no,     -,  missing candidates            A/B (> 1 candidate)
name, productpage, in progress, no/yes, v3, iteration 8, error            A/B
name, productpage, completed,   yes,    v3, traffic to baseline/winner    A/B
```

We defined the experiment types as: 

- performance (no candidate) no reward
- canary (1 candidate) no reward
- a/b (1 candidate) with reward
- a/b/n (> 1 candidate) with or without reward
