### ISSUE TITLE
Fix CRD documentation

### ISSUE THREAD

**Issue by fabolive** [iter8-tools/iter8#30]
I think we need to indicate that `trafficStepSize` does not apply to the Bayesian algorithms and Epsilon Greedy. Also, we need to indicate that `sample_size` (under the success criteria) does not apply to the Bayesian algorithms and Epsilon Greedy.

Do you confirm, @sriumcp / @sushmarchandran?

**Comment by sushmarchandran** [comment]
@fabolive :
1.  `trafficStepSize` applies only to Check and Increment. It does not apply to Epsilon Greedy and PBR/OBR.
2. `sample_size` applies to both Check and Increment and Epsilon Greedy algorithms. It does not apply to PBR/OBR algorithms only.
Also FYI: The sample size query template that comes from the iter8 metrics config map applies to all algorithms. However it is not a part of the Experiment CRD documentation.

**Comment by fabolive** [comment]
Done. Pushed these changes and made them part of release v0.0.1
