### ISSUE TITLE
Change tutorials to use a different fake domain for the sample app

### ISSUE THREAD

**Issue by fabolive** [iter8-tools/iter8#32]
The domain `bookinfo.sample.dev` is an https only domain and may cause unwanted browser redirects.

**Comment by kalantar** [comment]
Reported for docker for desktop environments

**Comment by kalantar** [comment]
@fabolive propose changing `bookinfo.sample.dev` to `bookinfo.example.com`

See changes in https://github.com/iter8-tools/iter8-controller/tree/master/doc/tutorials/istio/bookinfo-v1.0 and corresponding doc https://github.com/iter8-tools/docs/pull/87

**Comment by kalantar** [comment]
This has been done in those already written and will be continued in new ones as well. Consider this done.
