### ISSUE TITLE
remove rbac rules for knative resources

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#329]
Delete there rules: 

https://github.com/iter8-tools/iter8/blob/master/pkg/controller/experiment/experiment_controller.go#L271-L274:

    // +kubebuilder:rbac:groups=serving.knative.dev,resources=services,verbs=get;list;watch;update;patch
    // +kubebuilder:rbac:groups=serving.knative.dev,resources=services/status,verbs=get
    // +kubebuilder:rbac:groups=serving.knative.dev,resources=revisions,verbs=get;list;watch
    // +kubebuilder:rbac:groups=serving.knative.dev,resources=revisions/status,verbs=get

It seems I have to grant the iter8-operator all the same authority as the manager has if I want to create rbac rules from it. Noticed this set of older rules needs to be removed.

**Comment by sriumcp** [comment]
Done.
