### ISSUE TITLE
iter8 should not start an experiment until all (deployment) candidates are ready to take traffic

### ISSUE THREAD

**Issue by fabolive** [iter8-tools/iter8#365]
Today, as soon as the controller detects that all candidates have been deployed, it starts the corresponding experiment. It seems that even before the candidates are READY TO RECEIVE TRAFFIC, we start the experiment. We need to fix this behavior, otherwise we allow user requests to be sent to pods that are not quite ready yet.

As part of this item, we need to figure out how to interpret the status of a deployment object as an indication that the underlying pods will be able to respond to user requests. For instance, when we run `kubectl get deployments`, we see something like:

```
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment   0/3     0            0           1s
```

Perhaps we need to make sure that the deployment is `AVAILABLE`? This could be the right `Condition` to check for. Again, the correct check needs to be verified so that the implementation achieves the desired effect mentioned above.

**Comment by kimikowang** [comment]
Not applicable to service case.

**Comment by kimikowang** [comment]
And handling this case will break the current controller design. IMO, it's user's responsibility to set a long-enough duration to ensure a valid result.

**Comment by fabolive** [comment]
In this issue let's focus on the case where baseline and candidates are expressed as deployments.

**Comment by fabolive** [comment]
cc: @kalantar
