### ISSUE TITLE
Explore IBM Reseach twitter for kui and mlops/canary blog amplification

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#379]
Related to epics https://app.zenhub.com/workspaces/iter8-5e8231e5559a7027a3e7a971/issues/iter8-tools/iter8/303 and https://app.zenhub.com/workspaces/iter8-5e8231e5559a7027a3e7a971/issues/iter8-tools/iter8/349

**Comment by sriumcp** [comment]
Done.
