### ISSUE TITLE
Iter8.tools search is broken

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#431]
The preliminary does not seem to be broken. I can try pull changes. However, the file where the error originates from has not been changed. I also verified that the same file has not been updated from the theme recently.

**Comment by Alan-Cha** [comment]
The issue seems to stem from the fact that we are using a redirect (from v1-0-0.iter8.tools to iter8.tools) and there is a problem with CORS.

**Comment by sriumcp** [comment]
Fixed with the latest version.
