### ISSUE TITLE
Run "Explore iter8" split test and document process

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#433]
The [Netlify tutorial](https://docs.netlify.com/site-deploys/split-testing/#send-to-google-analytics) that I was following was somewhat misleading. I was not aware that I needed to also configure the custom dimensions on Google Analytics.

I am currently in the process of doing so with the help of [this tutorial](https://www.gatsbyjs.com/docs/ab-testing-with-google-analytics-and-netlify/).

**Comment by Alan-Cha** [comment]
Created the custom dimension

**Comment by sriumcp** [comment]
Closing for now.
