### ISSUE TITLE
[knative] Update mirroring tutorial

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#561]
**Is your feature request related to a problem? Please describe.**
When executing the following step of the tutorial:

    kubectl apply -f $ITER8/samples/knative/mirroring/routing-rules.yaml

I get this warning:

    Warning: using deprecated setting "mirrorPercent", use "mirrorPercentage" instead

We should update `routing-rules.yaml` to avoid this.

Expect no warning when running the tutorial

**Comment by sriumcp** [comment]
I tried doing this... and found that Istio's documentation is not working as promised (I am not sure if mirrorPercentage is actually implemented ... they might have documented it a bit too early!)

**Comment by kalantar** [comment]
> I tried doing this... and found that Istio's documentation is not working as promised (I am not sure if mirrorPercentage is actually implemented ... they might have documented it a bit too early!)

Oh well.. Guess no point in keeping this issue open then.
