### ISSUE TITLE
[Testing] dump() shell function is replicated

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#629]
**Is your feature request related to a problem? Please describe.**
`dump()` shell function is used in all the `check.sh` files associated with e2e tests. However there is code replication happening here. Eliminate this duplication.

**Why is the feature useful for Iter8 users?**
This does not help Iter8 users in anyway. It does make the life of Iter8 developer easier. There is lesser code to maintain / track and lesser potential for diverging variants and lesser need to ensure consistency if we avoid code duplication.

**Describe the solution you'd like**
Factor out dump() in a separate script, source it in other files and use the function.

**Describe alternatives you've considered**
Leave things as it is... but then, code duplication is not a good practice for reasons mentioned above.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
This does not require design discussions... just simple factoring.

**How will this feature be tested?**
[ ] The feature pertains to existing tests already. This is not an Iter8 feature, but change to the way tests are written.

**How will this feature be documented?**
No documentation required. Please see above.

**Comment by kalantar** [comment]
No longer about the dump() method which has been removed; instead we leave the cluster running for debug purposes. Instead, we have common methods to report a failure and to do check object field values. This has been done for the istio examples but needs to be extended everywhere.
