### ISSUE TITLE
[Enhancement] [Repurposed issue] Developing a new `candidate` CRD for Iter8

### ISSUE THREAD

**Issue by huang195** [iter8-tools/iter8#692]
This is to document a Slack discussion, regarding the following issue:

I'm creating an experiment CR resource without having deployed the candidate version in the cluster yet, and I was expecting that the experiment was going to be in some sort of paused state (IIRC that's version 1's behavior). However, what I observed what the experiment started to run even without the candidate version deployed. Is this the current expected behavior?

```
$ kubectl get experiments.iter8.tools
NAME               TYPE     TARGET                STAGE       COMPLETED ITERATIONS   MESSAGE
gitops-exp-17713   Canary   default/productpage   Completed   10                     ExperimentCompleted: Experiment Completed
```

and the candidate pod is not running

```
$ kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
details-v1-7876c8fb77-t67ck          1/1     Running   0          2m33s
productpage-stable-897b84d99-s8z9x   1/1     Running   0          2m33s
ratings-v1-6bd96496f7-g9wn4          1/1     Running   0          2m33s
reviews-v2-8565d9b857-hfwr8          1/1     Running   0          2m33s
```

Summary of the discussion so far is:

@sriumcp is suggesting that task framework is the right place to check and pause an experiment when this scenario happens (i.e., candidate not yet deployed). 

My view is this is a valid suggestion as the task framework is generic enough that such things could be done there. However, I wonder if such complexity should be exposed to users in the form of a task, as I couldn't think of any reason why someone would start an experiment without all the components being ready, e.g., candidate an baseline deployed. If that's true, iter8 should check for this condition internally before starting the experiment.

**Comment by sriumcp** [comment]
Subsumed by #948
