### ISSUE TITLE
[Feature Request] Allow for different types of actions that distinguish between finish, promote and fail

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#693]
**Is your feature request related to a problem? Please describe.**
Related to iter8-tools/iter8#644 and https://github.com/iter8-tools/etc3/issues/201

Today when a failure occurs, the finish actions are executed to allow the user to execute any last steps. In particular, to roll back if desired. However, if the failure happens early enough or without a valid weightObjectRef, the finish actions themselves will fail hiding the source of the actual problem from the user. In part this happens because we combined the notion of finish action with that of a failure action on the erroneous assumption that failure behavior meant roll back; ie same as a finish action.

Instead we should probably consider more fine-grained notions such as promote, finish and fail allowing the user to implement the behavior they want. Another issue will be created for this discussion.

**Why is the feature useful for Iter8 users?**
User can more precisely define when certain tasks should be run. Writing the actions becomes easier since different situations are already delineated.

**Describe the solution you'd like**
Open for discussion beyond the simple notion of distinguishing between promotion, finish and failure.

**Describe alternatives you've considered**

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
After discussion

**How will this feature be tested?**
TBD

**How will this feature be documented?**
TBD

**Comment by sriumcp** [comment]
@kalantar This issue seems to be missing a title?  Please edit appropriately.

**Comment by sriumcp** [comment]
This issue is outdated since finish actions are no longer auto-triggered on failure.
