### ISSUE TITLE
Cleanup logging in etc3

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#694]
etc3 currently seems to be using at least four types of log providers -- zap logging in main.go, go-logr (as seen from the go.mod file), "sigs.k8s.io/controller-runtime/pkg/log" in experiment_test.go, and util.Logger (because, this is where we want to control everything related to logging -- centrally).

I didn't look carefully, it is possible I missed other log providers here.

etc3 codebase needs to be cleaned up so that there is a single way to setup logging (in util) and use it everywhere, including controller setup, reconcile loop, and tests.

**Comment by sriumcp** [comment]
Please see https://github.com/iter8-tools/handler/blob/main/utils/utils.go for a simple pattern for defining the logger once and reusing it everywhere else in a simple and sane manner.

**Comment by kalantar** [comment]
I have reviewed the code and see only references to 2 logging libraries.  The `main.go` and the `suite_test.go` files use ("sigs.k8s.io/controller-runtime/pkg/log/zap") `zap.New()` to create a ("github.com/go-logr/logr") `logr.Logger`.  Everywhere else uses `github.com/go-logr/logr`.

`zap` is used only to create and configure a new Logger. It is introduced as the method of preference by the kubebuilder code generation. I see no reason to replace it.  The `logr.Logger` that is created is a property of the `controllers.ExperimentReconciler` created in `main.go` and is used everywhere else. It is passed to all methods via a context (`util.go` provides a method to extract it from the context).

I'm closing this as nothing to do.

**Comment by sriumcp** [comment]
Looks like "sigs.k8s.io/controller-runtime/pkg/log" is now gone. Which is good.

However, using two different logging packages in the same project is one logging package too many. For starters, logging format is going to be non-uniform. Reopening the issue. I can handle the issue as part of #908 (which is all about logging formats).

Also note: the handler repo has a cleaner approach to logging. Not only is there a single logger (`logrus`), it is possible to use the logger within Ginkgo tests (and not wait until the test fails in order to see the logs; you can see the log even if tests are passing, by setting the appropriate log levels), which is useful for dev time debugging purposes.

**Comment by kalantar** [comment]
The controller requires us to set a logger; it tasks a logr.Logger as in input for this. logr.Logger is an interface. An implementation is provided by zap. One needs only use it to set the logger; thereafter one uses the interface methods. We are not using 2 different loggers at different times with different formats. We are using one.

It appears that you prefer logrus. Unfortunately, it is not suitable for the controller; it does not provide an implementation of logr.Logger.

I still believe this should be closed.

**Comment by sriumcp** [comment]
Thanks for that explanation @kalantar.

I see `"sigs.k8s.io/controller-runtime/pkg/log/zap"` imported in `main.go`.
I also see `github.com/go-logr/logr v0.3.0` imported in `go.mod`. 

Aren't these different logger implementations?

The zap logger implementation is being set in the manager (which makes sense of course). 

Why is the second implementation showing up in `go.mod`?

***

This issue is not related to `logrus`. My comment on `logrus` was intended to point to the handler repo, which manages to use a single logging implementation consistently throughout the package instead of two.

**Comment by kalantar** [comment]
`github.com/go-logr/logr` defines the interface `logr.Logger`.  The methods of this interface are used to do the actual logging everywhere in the controller.  zap  is only used in `main.go` to create an instance of a logger that satisfies the definition of the interface `logr.Logger` (the interface type). The concrete instance is stored by the controller and then used via the interface methods.

**Comment by sriumcp** [comment]
Thanks @kalantar again for this explanation.

I understand now. I agree there is no issue here. Closing.
