### ISSUE TITLE
[Feature Request] Display reward(s) in their own table in output of iter8ctl describe

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#698]
**Is your feature request related to a problem? Please describe.**
When doing A/B and A/B/n tests, rewards should be highlighted by giving them their own section of output.

**Why is the feature useful for Iter8 users?**
This will enable users to see the rewards easily, understand the preferred direction and current values.

**Describe the solution you'd like**
Special section of output for rewards, something like:

    +---------------------------+-------+-------+
    |           REWARD          |   A   |   B   |
    +---------------------------+-------+-------+
    | books-purchased (high)    |   5   |   20  |
    +---------------------------+-------+-------+

**Describe alternatives you've considered**
By default they appear in the list of metrics. This does not help understanding that the metric is a reward metric and which direction if preferred.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Discussion in issue is probably sufficient.

**How will this feature be tested?**
- [ ] No reward section when there are no rewards in the experiment
- [ ] rewards section when there are rewards in the experiment

**How will this feature be documented?**
Could be documented in the README with another example. Not sure this is required.

**Comment by sriumcp** [comment]
@kalantar Go vet failed ... when checked with the PR merge.

1. This means, we need to add `go vet` to pull request workflows as well not just push workflows in GitHub Actions.
2. The failure due to `go vet` needs to be addressed.

I created an issue for 1 above... here: https://github.com/iter8-tools/iter8/issues/708

**Comment by sriumcp** [comment]
Done.
