### ISSUE TITLE
[Feature Request] Upgrade install tag v0.5.1 --> v0.5.2

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#709]
Now that iter8-install has been updated to version v0.5.2, we should update install.sh and the platformsetup.sh scripts in the user documentation.

**Why is the feature useful for Iter8 users?**
Ensures that the latest version of Iter8 is installed; it most closely aligns with the documentation.

**How will this feature be tested?**
Existing test cases should pass

**Comment by sriumcp** [comment]
I guess `install.sh` = `install.md` above?

**Comment by kalantar** [comment]
> I guess `install.sh` = `install.md` above?

Yes. Also, I see `iter8_install_tag: v0.5.1` in _mkdocs/mkdocs.yml_. I don't see it used anywhere. Does it have a purpose?

**Comment by sriumcp** [comment]
`iter8_install_tag` used to have potential :) Will remove it... can be reintroduced if needed.
