### ISSUE TITLE
[Feature Request] Run Iter8 within an OpenShift cluster

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#720]
**Is your feature request related to a problem? Please describe.**
OpenShift has a notion of Routes which both a precursor to K8s ingress and also a bit more feature rich than K8s ingress. Explore how to make Iter8 work with OpenShift routes.

**Why is the feature useful for Iter8 users?**
This feature is a starting point for using Iter8 inside an OpenShift cluster.

**Describe the solution you'd like**
Run Iter8 inside a MiniShift (or any OpenShift) cluster. Ignore metrics for the time being... try and get Iter8 to shift traffic using the route resource. RBACs needed to enable this have to be part of Iter8 install.

**Describe alternatives you've considered**
OpenShift serverless and OpenShift service mesh. Both of them require significantly more resources than routes option. Both  of them have  fewer users than the route / ingress option.

**How will this feature be tested?**
This is an exploratory task. No testing is required at this stage. Just a prototype / demo of Iter8 working within OpenShift and using OpenShift routes.

**How will this feature be documented?**
This is an exploratory task. No documentation is required at this stage.

**Additional context**
Under the covers, routes can leverage HAProxy (OpenShift's default and builtin ingress controller) to do stuff.  

[Kubernetes Ingress vs OpenShift Route](https://www.openshift.com/blog/kubernetes-ingress-vs-openshift-route)

**Comment by kalantar** [comment]
One possible option would be [minishift](https://www.okd.io/minishift/). Using the latest version (v1.34.3+4b58f89) I was able to successfully start a cluster using the following command: 

    minishift start --vm-driver=virtualbox --openshift-version latest

The lastest version of openshift that seems to be supported is 3.11.0. This is too old for our purposes.

**Comment by sriumcp** [comment]
Yes, that looks too old indeed with OpenShift on 4.7? 

I agree we don't have to  use `minishift` if it doesn't serve our purposes. We could have used it for local dev had they invested in maintenance :)

**Comment by kalantar** [comment]
[Code Ready Containers](https://developers.redhat.com/products/codeready-containers/overview) may be another alternative for local development/demonstration. It starts and provides OpenShift 4.7. However, it seemed to stop working when I tried to install OpenShift Pipelines and again trying to install Service Mesh. It more or less recovers after stopping and restarting. Not sure if it is stable enough to be effective.

**Comment by kalantar** [comment]
The following settings can be used to configure resources:

    crc config set cpus 8
    crc config set memory 20480

With these settings I was able to install the Openshift Pipeline and Service Mesh operators and to use the latter to install istio.

**Comment by sriumcp** [comment]
Done.
