### ISSUE TITLE
[Feature Request] Simplify the process of creating iter8-install artifacts

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#722]
**Is your feature request related to a problem? Please describe.**
Creating iter8-install artifacts for a new domain, or modifying them for an existing domain is currently a roundabout process. There  are  two repos. There's an auto-PR. Platform setup needs to change each time iter8-install versions are updated.

Simplify this.

**Why is the feature useful for Iter8 users?**
Simplifies life for Iter8 contributors.

**Describe the solution you'd like**
1. Move install under Iter8 repo (instead of a separate repo)
2. Use `kustomize build | kubectl apply -f -`  ; this introduces kustomize dependency during install but eliminates the need for auto PR.
3. Convert all tests to use `kustomize build install-folder-from-master | kubectl apply -f -`. This eliminates the need to change platform setup each time install is updated. This still continues to pin specific versions of etc, handler, and analytics (i.e., we will not use master/latest tags for those images as part of install; we will use pinned versions as we do now).

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Please see above.

**How will this feature be tested?**
Yes, existing integration/e2e tests need to work.

**How will this feature be documented?**
Yes, there will be new documentation how to update install and how to integrate a new K8s domain.

**Comment by kalantar** [comment]
> this introduces kustomize dependency

We chose to eliminate this dependency in the past to make the user experience simpler at the expense of complexity on our part. Why do we feel that it worth adding it back?

**Comment by sriumcp** [comment]
Bringing back Kustomize is really meant to simplify dev.

From a dev perspective, Kustomize build eliminates the need for the auto-PR (which is an error-prone manual process). Eliminating the auto-PR simplifies pushing changes to the install repo.

Incidentally, Flagger has a helm dependency (and also a kustomize dependency) depending on how users choose to install it... perhaps it is fine to use one of these standard installation mechanisms, given how popular both of them are?

**Comment by kalantar** [comment]
At one time we tried `kubectl kustomize` but there was a version issue. Is there a version of kubectl we could require that would address this?

**Comment by sriumcp** [comment]
@kalantar Great catch.  I was able to verify with my `kubectl v1.20.0` client that `kubectl kustomize github.com/kubernetes-sigs/kustomize.git/examples/helloWorld?ref=v1.0.6` works, which is all that we need  for the above feature.

I can experiment a bit with the minimum kubectl versions needed to make the above command work... but I suspect v1.20+ should be ok for `kubectl`.

**Comment by sriumcp** [comment]
I take the above comment back: https://github.com/kubernetes-sigs/kustomize#kubectl-integration

kustomize integration with kubectl has remained frozen and hasn't moved forward.

I now remember the issue.. while remote folder can be kustomized as above, the kustomization files themselves do not allow for remote refs (in kustomize v2.0). This issue is rectified in v3.0 (which is the reason why we're using v3.0 in our our kustomize builds).

**Comment by kalantar** [comment]
Ok. I know there is a tradeoff between dev and user simplicity and agree that the PR has been a challenge. I'm not opposed, just wanted to make sure we gave it another moments of thought.
