### ISSUE TITLE
[Feature Request] Enable webhook notifications from iter8 experiments

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#731]
**Is your feature request related to a problem? Please describe.**
Support for notifications is a common request. In this context, webhooks and [slack](https://github.com/iter8-tools/iter8/issues/689) are usually mentioned. This issue is for a generic webhook notifcation.

Why is the feature useful for Iter8 users?
Allows users to find out about experiment progress from webhook notifications.

**Describe the solution you'd like**
The simplest approach is to enable users to specify how to send notifications from tasks. This can be done at the start, at loop boundaries and at the end. A specific task `notification/webhook` could send a standard notification and would be simple to specify in the list of actions.

Need only support POST method and a fixed body (the experiment).
Needs to support placeholders in the URL and headers similar to what is done for metrics to allows specification of an authorization method.

**Describe alternatives you've considered**
Other alternatives involve registration either via another component or new CRs. A task provides a relatively straightforward means to get feedback on approach.

**How will this feature be tested?**
TBD

**How will this feature be documented?**
A section will be created in the notification tasks page of the References documentation.

**Why is the feature useful for Iter8 users?**
How will this feature add value to Iter8 users and improve Iter8 experiments.

**Additional context**
This is related to the idea of a more general http-request function as proposed [here](https://github.com/iter8-tools/iter8/discussions/724). The notification task could be implemented using it.

**Comment by sriumcp** [comment]
Fixed.
