### ISSUE TITLE
[Feature Request] Bash task to replace/augment common/exec

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#733]
**Is your feature request related to a problem? Please describe.**
A common use for the common/exec task is to set `cmd: bin/bash` and to have the first argument be `-c`. Instead, provide a task that takes just a script as an argument and runs it as a script. This simplifies expression for the user.

In addition, we can eliminate the need for disableInterpolation; we can determine if versionRecommendedForPromotion has been set or not as part of the processing.

**Why is the feature useful for Iter8 users?**
Simpler expression. Very common pattern in the task we have created thus far.

**Describe the solution you'd like**
Introduce `common/bash` as a new task. It would allow expression as:

      - task: common/bash
        with:
          script: | 
            kubectl -n bookinfo-iter8 apply -f {{ .promote }}

**Describe alternatives you've considered**
There are other options for naming such as common/run. I think being explicit that it is a bash script is probably helpful to the user.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
This issue can be for design. Propose to add the task as an experimental task. That is, add it. But not necessarily document it. We can use it, get feedback and refine it (or throw it away).

**How will this feature be tested?**
Unit tests for creation, validate any interpolation changes.

**How will this feature be documented?**
Initially, not documented. If promoted from experimental, would document as part of references tasks.

**Comment by sriumcp** [comment]
@kalantar {{ .promote }} still comes from version recommended for promotion. Is this correct?

Also, what happens if this task is invoked and there is no version recommended for promotion in the experiment?

**Comment by sriumcp** [comment]
I feel this is a significant improvement (in terms of user experience, ease of use and readability) over the existing `common/exec` task.

**Comment by kalantar** [comment]
> @kalantar {{ .promote }} still comes from version recommended for promotion. Is this correct?
> 
> Also, what happens if this task is invoked and there is no version recommended for promotion in the experiment?

Good question. The second merits some discussion.

At to the first, yes. {{ .promote }} will come from recommended version. The code now creates the list of tags as follows:

	tags := base.NewTags().
		With("this", obj).
		WithRecommendedVersionForPromotion(&exp.Experiment)

In this case, `obj` is the experiment converted to a map[string]interface{}. Any variables from the version recommended for promotion are also added.   If there is no version recommended for promotion, these are not added.

Instead of implementing a disable interpolation behavior, I chose to go ahead and interpolate. The result is *different* from the past, "hello {{.name}}" will become "hello " instead of "hello {{.name}}". An alternative template package (text/template instead of http/template) produces "hello \<not found\>".  I thought that probably the user will have problems in any case.

A user should be able to do something like: 

    CAN_PROMOTE={{.this.status.versionRecommendedForPromotion}}
    if [ -z ${CAN_PROMOTE} ]; then
        exit
    fi

**Comment by sriumcp** [comment]
@kalantar What is needed in order for this to promoted as non-experimental?

This looks like a fantastic alternative to the current `common/exec` and it is better if it is documented, so that it can be used in tutorials.

Could we remove the `exploratory` tag from this issue, and add the documentation requirement as part of it?

**Comment by sriumcp** [comment]
Done.
