### ISSUE TITLE
[BUG] Number of loops seems incorrect

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#734]
**Describe the bug**
When `maxLoops` is greater than 1, Iter8 executes an experiment `maxLoops - 1` times instead of `maxLoops` times.

**To Reproduce**
1. Take any experiment with a loop action.
2. Set numIterationsPerLoop to 1
3. Set maxLoops to 10

You will see that the experiment completes 10 iterations and 9 loops.

**Expected behavior**
In the above example, I expect the experiment to complete 10 iterations and 10 loops.

Perhaps `moreLoopsNeeded()` function needs to be introduced just like `moreIterationsNeeded()` in https://github.com/iter8-tools/etc3/blob/main/controllers/iterate.go

**Comment by kalantar** [comment]
How do you measure the number of loops. I recall that we decided not to call the loop handler on the last loop. I suspect given some of our use cases, that we want to reconsider this choice.

That is, I think it is doing 10 loops but recording only 9 and not the 10th. Will check.

**Comment by sriumcp** [comment]
By default, each `metrics/collect` action sends 40 requests.

[This experiment](https://github.com/sriumcp/iter8/blob/builtins/samples/knative/conformance/experiment.yaml) should have sent 400 requests before finishing. It sends 360 instead.

**Comment by kalantar** [comment]
The metrics/collect action is executed in a loop action. Hence the decision to skip the last loop action would be a cause. This is the behavior that needs to change. This is a good change. I feel that it makes the behavior easier to understand -- it is more like an intuitive behavior.
