### ISSUE TITLE
Simplify quickstart tutorials

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#741]
**Description:**

**Note:** Although the following simplifications are discussed in the context  of quick start tutorials,  they affect all the tutorials. This is because steps from the quick start tutorials are re-used in other tutorials. So, while refactoring Quickstart, we need to keep this in mind.

- [ ] use builtin metrics
- [ ] use synthetic metrics
- [ ] eliminate fortio yaml files (since load / metrics will now be handled entirely by the above two)
- [ ] eliminate all the prometheus installs (again because of the first two simplifications); given  the popularity of Prometheus, it is worth adding a separate Prometheus & Grafana tutorial for all K8s stacks. But there is no need to sprinkle Prometheus in every tutorial and complicate them.
- [ ] use `bash` instead of `exec` task -- this will cut out a few lines from experiment  yaml and also make it less cryptic
- [ ] separate the platform setup steps  -- a user who already has a K8s cluster with a specific K8s stack installed on it, should be able to start by installing Iter8 and continue with the rest of the tutorial (instead of having to start with fresh cluster)
- [ ] introduce helm templates for experiments; our main motivation here is to ensure that a user can start using the quick start tutorial for their own apps/ML models without having to understand **anything** about Iter8.  Helm templating with well thought out values (and clearly documented assumptions that are made by the template in terms of the app/ML model manifests), can help with this.
- [ ] verify that `iter8ctl` output is adequate in terms of explainability (it probably is sufficient for now; but ensuring loop behavior works as expected; formatting is decent, etc., can help improve the value from this tutorial).

**Comment by huang195** [comment]
I like these suggestions. In the GitOps tutorial, I was already trying to simplify things, but not to the extend that you are suggesting, so the tutorial can be more focused on GitOps issues. 

The GitOps PR is under review, so do you want to hold off on that until all the other tutorials are updated with the proposed change?

**Comment by sriumcp** [comment]
I think the GitOps tutorial review can continue. There might be other issues (not simplification related) which may need to be resolved anyway.

I like what you said  -- create an initial version, and continue to Iter8 on it until we feel we've something simple enough and go to town with :)

**Comment by kalantar** [comment]
I would like to suggest that we consider splitting this into multiple issues to make implementation and review simpler. In particular, I would like to see the helm templates done as a separate issue. I think it requires more thought and perhaps design discussion as we figure out what well thought out parameters are.

**Comment by kalantar** [comment]
I like the move towards simplification. But I feel a little that perhaps the user will face the difficulty of figuring out how to make the example practical. Perhaps we need a new page of documentation that addresses this question.  That is, considerations for applying iter8 to a real application/model.

**Comment by sriumcp** [comment]
We can  definitely consider adding a new page of documentation... but it would be better if the Helm params are well thought out so that it is drop dead simple for the user to try the experiment with their real application after reading the tutorial, without having to read yet another documentation on what it means for them.

In other words, it would be preferable to write the tutorial in such a way that it accomplishes the above purpose.

**Comment by kalantar** [comment]
It isn't just helm that I am thinking about. Replacing metrics. Replacing load generation (with live traffic). These are all considerations. We don't have to have formulas. But a list of considerations would be valuable.

**Comment by sriumcp** [comment]
Both those considerations (replacing metrics and load generation) make sense.

This is especially true for A/B testing experiments... for SLO validation experiments, builtin metrics + builtin load generation might actually offer more advantages. Anyway, I agree that these considerations are worth documenting.

**Comment by SharpEdgeMarshall** [comment]
I'm new to iter8 and I'm having a hard time trying to understand how built-in metrics works.
Am I forced to generate fake traffic using collect or can I send live traffic to the experiment?
I think the documentation should explain more this high level concepts

**Comment by sriumcp** [comment]
Hi @SharpEdgeMarshall 

Welcome to Iter8.

Built-in metrics already do the job of sending traffic to your applications and collecting metrics. So, you do not have to do any load generation separately. So, the traffic is fake, but the metrics are real (based on how your app performs with regards to this fake traffic).

***

https://iter8.tools/0.7/getting-started/first-experiment/ is an example of an experiment that sends (synthetic) traffic to an application's API endpoint and collects latency and error rate metrics.

https://iter8.tools/0.7/tutorials/deployments/slo-validation-payload/ is another example where the experiment sends (synthetic) traffic to an application's POST endpoint (HTTP requests with payload) and collects latency & error rate metrics.

***

Any suggestions you might have in terms of improving the documentation is very welcome. We would love to hear your suggestions.

***

You might also interested in the upcoming Iter8 community meeting (Wed 11.00 AM Eastern Sep 29th, which is all about Iter8 built in metrics!!).

**Comment by sriumcp** [comment]
You can of course run Iter8 experiments with live traffic.

If you want to use live traffic, the metrics need to be collected in a database (example Prometheus; it can be any DB). Iter8 does not "intercept" your live traffic; however, assuming you are collecting metrics for live traffic in a DB, Iter8 does have the custom metrics capability which can utilize metrics from any database, collected by you for your app, during an experiment.

**Comment by SharpEdgeMarshall** [comment]
@sriumcp Thank you for your prompt answer.
Yes I was near to understand that built-in metrics works only with `metrics/collect` but this is not explained very well.
ATM we are evaluating iter8 to do ML canary releases, based on the fact that ML services are idempotent and pure I think that the best testing strategy would be using mirroring but also this part is not explained in v0.7, looking at v0.6 there was some sort of explanation with istio but it's not clear what's the intended approach.

**Comment by sriumcp** [comment]
Thank for the feedback re: docs. We can certainly document builtin metrics better, and will do so shortly.

***

Re: mirroring, what ingress/service mesh are you using to achieving the traffic mirroring function? Istio? And also how are you collecting metrics for the mirrored traffic (/shadow deployment of your app)? Which DB is the metrics stored in? We might be able to describe/document a simple example if we have some understanding of your setup.

***

Iter8 experiments can simply co-exist alongside your service mesh / ingress specs, so you can certainly run an experiment using mirrored traffic in Iter8. I think we can also make this a bit clearer through tutorials. We will do this also soon.
