### ISSUE TITLE
[Enhancement] Enable generation of synthetic metrics in analytics service

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#742]
**Is your feature request related to a problem? Please describe.**
Currently, metrics mock is a tedious process. First, it requires an extra service (metrics-mock), and YAML files for its configuration, and more YAML files for its deployment. 

This seems too much work to generate synthetic metrics.

Simplify this by builtin synthetics within the analytics service and by extending the metrics CRD.

**Why is the feature useful for Iter8 users?**
This will eliminate the need for metrics-mock service in A/B testing tutorials. Metrics mock can be substantially simplified, leading to easier tutorial creation and also easier explanations / ways to exercise the tutorial.

**Describe the solution you'd like**
```yaml
apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: user-engagement
  namespace: iter8-istio
spec:
  mock: 
  - name: sample-app-v1
    level: 25.0
  - name: sample-app-v2
    level: 50.0
```
> Note: `mock` is an optional field with a list of versions and their levels; when this field is present, analytics service will ignore other parts of the metrics resource, and generate random values for metrics instead of performing queries to databases.

> Note: `Gauge` is the default type for all metrics: builtin, custom, or mock.

**Describe alternatives you've considered**
Use current metrics-mock. Significantly complicated.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes. Please see example above.

**How will this feature be tested?**
- [x] Unit tested within Iter8-analytics service
- [x] Unit tested within etc3
- [x] Integration tested as part of all A/B testing tutorials

**How will this feature be documented?**
- [x] metrics documentation at Iter8.tools will be extended with this mock feature.
- [x] since the idea is combine this issue with #751, documentation needs to reflect this as well.

**Comment by huang195** [comment]
Looking at this issue when reviewing https://github.com/iter8-tools/etc3/pull/210, a Metric with a defined synthetic field is a bit confusing to look at because it now contains 2 fields: i) to query real systems, and ii) to return synthetic numbers. Using the above example, would it be more clear to say

```yaml
  type: Synthetic
  provider: Iter8
  params:
  - name: sample-app-v1 # name is the name of the version
    level: 25.0 # metric value will converge to 25.0 over time for this version
  - name: sample-app-v2
    level: 50.0 # metric value will converge to 50.0 over time for this version
```

and remove some of the other fields that are not relevant. The exact fields might not be what are stated above, but hopefully you get the idea.

**Comment by sriumcp** [comment]
I was a bit careless about the optional fields...cleaning up the example above in the spirit of what you said.

***

I wanted to keep the CRD changes to a minimum for this initial implementation of the feature... 

Currently, `type` is an enum that can be counter or gauge. We will probably want to keep it this way since these are fundamentally two different types of metrics (along the lines of a Prometheus counter or gauge).

In the current design, you can have a synthetic metric that is `counter` or `gauge`. The metric will be synthesized differently. Counter will keep on increasing over time (in proportion to time elapsed and the level). Gauge will converge over time to the level.

***

Further, `jqExpression` and `urlTemplate` are both required fields at the moment. I also agree that in the future they can evolve to become optional, which will simplify this further.

Both these changes happen to be non-breaking from an K8s API perspective, but require significant code changes to etc3/analytics in order to get it right. Something we can attack in a future issue.

***

@huang195

**Comment by kalantar** [comment]
Does this approach make the metric version specific? This seems awkward except for one time experiments.
In this case, it might make more sense to have the synthetic override in the experiment definition as an alternative to a reference to a metric object.

**Comment by sriumcp** [comment]
1. By definition, synthetics are intended for learning purposes (in particular, faking the metric value easily as part of tutorials). So, yes, they are indeed for one time experiments. Synthetics are not intended for actual production usage. The advantage of this approach is that it enables the user to start  entirely with synthetics, and gradually replace the synthetics with a real metric (simply by removing the synthetics field as part of the metric def).

> Note: I agree the above is not accurate. The content of the real metric needs to be filled and mock needs to be taken out. The advantage is in terms of the experiment yaml, which doesn't have to change, when going from a mock metric to a real one (assuming name/namespace are retained in the metric definition).
 
2.  Using the existing metric CR implies we can also use the existing mechanisms by which metric definitions find their way into experiments (i.e., etc3 will fetch it from the specified namespace). Inventing a new CR for synthetic is an overkill. Using other ways to insert synthetics in place of metrics objects does not seem more intuitive than the metric CRD extension above.

3. I believe this is the simplest way to introduce a way to fake the metric value. If there are alternative design that makes tutorials / learning objectives even simpler, I am definitely interested, but I am not seeing a concrete proposal yet in that regard.

**Comment by huang195** [comment]
IMO, the word `mock` sounds more better than `synthetic`

**Comment by sriumcp** [comment]
I am neutral to `mock` or `synthetic`. @kalantar Do you have a preference? I am ok with either.

**Comment by sriumcp** [comment]
Changing  the above example to use `mock` instead of `synthetic`.

@huang195 @kalantar If you are good with the updated example above, I will update the etc3 PR for synthetics accordingly.

**Comment by kalantar** [comment]
> By definition, synthetics are intended for learning purposes (in particular, faking the metric value easily as part of tutorials). So, yes, they are indeed for one time experiments. Synthetics are not intended for actual production usage. The advantage of this approach is that it enables the user to start entirely with synthetics, and gradually replace the synthetics with a real metric (simply by removing the synthetics field as part of the metric def).

I don't see this as a migration path. In practice, the user will need to define a new metric entirely. Replacement may just men keep the name and change everything else.

> Inventing a new CR for synthetic or using other ways to insert synthetics in place of metrics objects seems to incur too much work in terms of implementation.

Yes. An alternative would be more work. I am suggesting that the proposed solution, while easiest, is not suitable.

> I believe this is the simplest way to introduce a way to fake the metric value. If there are alternative design that makes tutorials / learning objectives even simpler, I am definitely interested, but I am not seeing a concrete proposal yet in that regard.

I agree that this may be the simplest approach to fake a value. However, I am not convinced that it is the right approach. It suggests to users that they need to modify the metric for every experiment. Other solutions (like the one proposed in the comments above -- to modify an experiment to specify these on an experiment by experiment basis) are more work. But that should not be a reason to dismiss them if they have merit in terms of clarity and use over the current proposed approach.

To be more concrete, I am suggesting that we modify an experiment to allow something more like:

```yaml
    objectives: # metrics used to validate versions
    - metric: iter8-istio/mean-latency
      upperLimit: 100
      mock: # this is an optional field with a list of version and their levels; when this field is present, analytics service will generate random values for metrics instead of performing queries.
      - name: sample-app-v1 # name is the name of the version
        level: 25.0 # metric value will converge to 25.0 over time for this version
      - name: sample-app-v2
        level: 50.0 # metric value will converge to 50.0 over time for this version
```
The presence of the `mock` field overrides any behavior defined in a `Metric` object if one exists. There would not be a requirement to actually have one defined (though it may be easier to start with the assumption that it is there).

**Comment by sriumcp** [comment]
In Iter8, there is a clear separation of concern between the following aspects of experimentation... 
1. Collecting metric values for different versions,
2. Deciding if objectives are satisfied,
3. Deciding which version is best performing in terms of the reward, and 
4. Reporting the results (enabling `iter8ctl describe`  in particular).

The approach I am proposing is intended to enable faking 1, while using existing mechanisms for 2, 3 and 4 with zero change. It is simple, in terms of simplicity of understanding, from the CRD change perspective, and the implementation perspective. 

It will be clear to the user (and will be clearly documented) that when there is a `mock` field in the metric definition, the metric value will be mocked!

***

Putting the `mock` within `objectives` as suggested above has the following disadvantages.

* We are also putting `mock` subfields for rewards, objectives, and indicators (additional complexity in terms of CRD changes). So, `mock`  is not appearing in  one place, but sprinkled in multiple places in the CRD.
* Whole lot more complexity in terms of analytics service changes, because the basic separation of concerns outlined above  are no longer honored by this design; analytics service is built with this clean separation in mind. The design alternative breaks this clean abstraction and conflates metric collection on the one hand with objective and reward assessment on the other; this will also end up making analytics code more brittle, less readable, and more difficult to contribute to.
* Repetition -- if the metric were to have upper and lower limits, then the mock section is repeated twice for the same metric.
* Reduced clarity for the end-user: why exactly is the mock field under objectives, rewards and indicators, when what is getting mocked is metrics?

***

If the idea is to fake metrics, I am unable to understand why is it better to put the mock fields under three different places, namely,`objectives`, `rewards` and  `indicators`; instead of going for the obvious and direct (**and simple**) option of putting it within the `metrics` resource.

***

@huang195 Perhaps you could chime in on the above alternatives as well...

**Comment by sriumcp** [comment]
Re: migration path, the user does get to retain the same *experiment.yaml* in the design I proposed, for both mock and real metrics. This does offer a clear migration path: start with a metrics mock, get the rest of the experiment in place as it needs to be, and then migrate to the real metric.

In the design alternative, this advantage is lost. The experiment yaml needs changing when going from fake to real metrics. Additionally, you will have to create metric resources anyway (because etc3 will fail the experiment if metrics are not present), the metrics resources are going to be fake (if they were real and functional, you wouldn't need mock metrics),  and therefore, the metric resources *also* need to be changed subsequently.

**Comment by sriumcp** [comment]
On further thought, I think it may be easy enough and makes sense to attack both this issue as well as the closely related issue #751 together.

#751 is definitely extra work. But it does make the mock metrics resource more intuitive from the end-user perspective. 

Incidentally, #751 will also have the highly desirable side effect of making builtin metrics more intuitive from the end-user perspective. The jqExpression and urlTemplate fields are currently filled with dummy values for builtin metrics... #751  seems like the right approach considering it will simultaneously achieve simplification for both builtins and mocks.

@huang195 Modifying [the example on top](https://github.com/iter8-tools/iter8/issues/742#issue-914142268) in line with this. The example above now looks almost the same as your suggestion (except for some minor variations).

**Comment by sriumcp** [comment]
> It suggests to users that they need to modify the metric for every experiment. 

How?

It suggests to users that they can get started with mock metrics, get the rest of their experiment right, and convert mock metrics into real ones. In other words, change in metrics happens once,  when going from mock to real.

> Other solutions (like the one proposed in the comments above -- to modify an experiment to specify these on an experiment by experiment basis) are more work. But that should not be a reason to dismiss them if they have merit in terms of clarity and use over the current proposed approach.

I agree we don't want to dismiss any solution just because it is more work.

However, the design alternative is more work in terms of implementation, breaks important abstractions, makes the analytics service brittle, and creates needless complexity for the end-user, all at once.

The design does not seem clean.

***

On the other hand, the proposed design, along with the idea of ensuring that the metric samples do not simultaneously show real and mock fields but shows only one of them at a time, although requiring more work (specifically, #751), does keep metric and experiment definitions simple and intuitive, and is therefore worth investing into.

It also respects the separation of concerns (1, 2, 3, and 4) outlined above.

**Comment by kalantar** [comment]
> Putting the mock within objectives as suggested above has the following disadvantages.

Agreed. It is not ideal and may not be the right approach. 

> Re: migration path, the user does get to retain the same experiment.yaml 

Probably true though I expect the referenced metric names will change. I expect users will not modify mocked metrics but replace them with new ones. In any case, in the process of replacing/redefining a metric it may also be necessary to add variables to the versionInfo of an experiment.

> there is a clear separation of concern between the following aspects of experimentation...

This is a valid separation that clearly defines the implementation principles behind the analytics engine. However, there is another dimension to separation that exists between that which is general and that which is experiment specific. In particular, we isolate version specific details to the experiment; indeed to the versionInfo section of the experiment spec. Version specific information is accessed via placeholders in actions and in metrics.

Both proposed solutions violate this principle. In one, version specific information (the name of the version) is placed in the Metric resource. In the other in the criteria section of the experiment. I prefer a solution which keeps the metric resource version independent; that just defines where the analytics engine will get its values. I agree with the limitations of the second solution (replication, need for change). However, it has the benefit of keeping information specific to a specific set of versions in a common object.

Perhaps we can find a third approach?

I looked at metrics-mock (which I have never really looked at before; I am not familiar with its implementation so likely forsee  any difficulties in modifying it. As you pointed out originally, it has the disadvantage that is is complicated to create the configuration file.  In part, this is because it requires the simulation of other databases. Could we for example, have a notion of a mock service that allows a very simple version, value kind of specification? A metric might look like:

```yaml
spec:
params:
  - name: version
    value: $name
jqExpression: “.”
urlTemplate: http://metrics-mock.iter8-system.svc.cluster.local:8080
```

In terms of migration/development, this allows a user to gradually complicate the Metric specification while continuing to mock if desired (taking advantage of the current capabilities of metrics-mock). Or to replace as needed with a real standard definition.

**Comment by sriumcp** [comment]
> Both proposed solutions violate this principle. In one, version specific information (the name of the version) is placed in the Metric resource.

When you mock metrics for versions, you need some way of specifying how to mock metrics for a specific version. This information needs to go somewhere. The metrics object itself is the obvious and natural place for it to go.

> In particular, we isolate version specific details to the experiment; indeed to the versionInfo section of the experiment spec. Version specific information is accessed via placeholders in actions and in metrics.

I agree that versionInfo section of the experiment is a natural place to stick in version specific information. But I disagree that all version specific information has to go only here. The version specific portion of the experiment YAML affords certain types of flexibility. Similarly, version specific portions of the `mock` subfield of metrics affords the type of simplicity and flexibility I am describing in the first proposal. 

What is the logic behind the argument that version specific information needs to be in experiment.yaml only and can never appear in metrics.yaml, even if it turns out that doing so can solve the mocking problem in a simple and intuitive manner?

TBH, I am not a fan of a having metrics definitions in metrics, and version specific information for metrics appearing in experiment in the first place. It makes the connection between metric queries and version details indirect and non-trivial to get it right. I wouldn't call it a mistake, but in my mind this was an expedient choice of implementation to start with, and by no means a clean design. I think there are better ways to specify metrics, by moving version specific portions of metrics into the metrics CRD. When Helm is used to instantiate an experiment template, it can be equally effectively used to instantiate the metric templates as well on a per-experiment based (but even that is unnecessary; most two-version experiments with promotion can have generic version names such as `baseline` and `candidate` which means metrics can be instantiated once and re-used across experiments).

@kalantar The reason behind the `mock` field of metric spec is to avoid the need of a third service, the metrics-mock.
I remember writing the metrics mock service, especially the difficulty in creating it and maintaining it (it is still not documented because it is a convoluted and non-trivial way of achieving the metics mock function). From the end-user perspective it is downright horrible. From the perspective of the tutorial author trying to create specific mocks for versions, it is an absolute nightmare.

While it allowed for initial mocking in our current A/B testing experiments, it has the disadvantage of complicating tutorials needlessly. It creates extra YAMLs for deployment, and more cognitive load for the user in terms of understanding.

I am glad you're starting to look into the metrics-mock service, but the third proposal does nothing to mitigate the above issues, exactly the type of issues which the **simple** and **intuitive** `mock` field in metrics CRD overcomes easily.

**Comment by sriumcp** [comment]
IMO, the primary purpose of this metrics mock feature is learning purposes (learn about experimentation without the complexity of a real database or yet-another service to be configured).

The secondary purpose of this metrics mock is migration. Get started with an experiment without the complexity of a real database or yet another service to be configured.

IMO, the `mock` field in metrics serves both these purposes well. The fact that it is simple to implement and easy enough to maintain is a desirable added bonus (I was able to fix my [etc3 PR](https://github.com/iter8-tools/etc3/pull/210) easily to accommodate this new design; the design change happens to be non-breaking).

I just do not understand  the need to complicate what is essentially a simple feature (I wish I had this understanding at the time of creating metrics-mock service... creating and trying to use that service definitely informed the proposed design).

**Comment by sriumcp** [comment]
Summarizing the proposals so far:

**Proposal described on top:** Introduce a single `mock` field in metrics CRD. This change is non-breaking and already handled by this [etc3 PR](https://github.com/iter8-tools/etc3/pull/210). Analytics service needs further changes to produce mock values for metrics. Eliminates the `metrics-mock` service from tutorials as well as from list of things to be maintained.

**Proposal number 2:** Change objectives, reward, and indicators portion of the experiment CRD. All the reasons why this is not a desirable change is discussed [here](https://github.com/iter8-tools/iter8/issues/742#issuecomment-857162377).

**Proposal number 3:** Don't change anything. Continue to maintain the metrics-mock service instead. This thread started with the purpose of eliminating the complexity of this additional mock-service, first from the end-user (i.e., the person exercising a tutorial) point of view, second from the tutorial creator point of view, and third from the Iter8 maintainer point of view. The proposed *third alternative* is actually what is happening today already in our tutorials.

**Comment by kalantar** [comment]
I think we are both concerned with a users learning process as they move from running a sample application on minikube to running their own application in their own cluster. We both want this process to be as straightforward and understandable as possible. I suspect that we have different conceptions of how this happens. It may be useful to try to sketch this out together. Identifying general steps and what needs to be changed. A shared understanding will certainly resolve this.

**Comment by sriumcp** [comment]
Fixed.
