### ISSUE TITLE
[Feature Request] Use new make targets in handler project workflows

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#746]
**Is your feature request related to a problem? Please describe.**
This change aligns the code in the workflow with any steps a developer would take to verify their code in advance of pushing.

**Why is the feature useful for Iter8 users?**
It benefits developers.

**Describe the solution you'd like**
Use make commands in workflow.

**Describe alternatives you've considered**
Could leave it as is.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
No.

**How will this feature be tested?**
Expect tests to continue to work

**How will this feature be documented?**
Not needed

**Additional context**
Not urgent

**Comment by sriumcp** [comment]
Obsolete.
