### ISSUE TITLE
[BUG] Error message not appropriate

### ISSUE THREAD

**Issue by huang195** [iter8-tools/iter8#760]
I'm playing with Openshift Route, and I'm getting the following error message after starting an experiment.

```
  - lastTransitionTime: "2021-06-09T15:30:38Z"
    message: Specification weightObjectRef invalid
    reason: InvalidExperiment
    status: "True"
    type: Failed
```

This most likely is due to me not setting up RBAC correctly for iter8 controller's service account to modify Openshift route for traffic shifting, but the error message seems to be not relevant. Looking at the code, the error message seems to be hard coded. Can we use the error message K8s API server gave? It should show more clearly why the K8s client API call failed.

I will need to verify whether or not this issue is due to RBAC, but just wanted to paste the error message here before I lose it.

**Comment by sriumcp** [comment]
Could you please post your experiment yaml here?

**Comment by sriumcp** [comment]
OTOH, @huang195 Its nice to know that you're running Iter8 on OpenShift :-)

**Comment by huang195** [comment]
@sriumcp after creating the necessary RBAC rules, Iter8 experiment runs  to completion, so the failure message is indeed not appropriate. You can recreate this problem on a K8s cluster by removing the rolebinding for iter8-controller service account so it can't update Istio VS.

**Comment by huang195** [comment]
> OTOH, @huang195 Its nice to know that you're running Iter8 on OpenShift :-)

Indeed, the flexibility added in the new architecture made switching from Istio VS to Openshift Route pretty straight forward.
