### ISSUE TITLE
Improvements to iter8 in Docker installation

### ISSUE THREAD

**Issue by sushmarchandran** [iter8-tools/iter8#773]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Iter8 in Docker can be better used if the following improvements can be made:
1. Iter8ctl can be installed by. the Dockerfile to enable more descriptive outputs displayed to the user.
2. Helm can be be installed in Dockerfile to start templating experiments

**Describe the feature/solution you'd like**
Solutions have been described above.

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Tekton and CE users of iter8 will find this solution useful. It improves the ease of use for iter8 using Docker.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Installing helm can help developers start templating experiment yamls

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Design discussion may be done after this feature is implemented to discuss how to create helm templates for iter8 experiments.

**How will this feature be tested?**
- [ ] This feature will be tested on CE environment

**How will this feature be documented?**
- [ ] N/A

**Additional context**
N/A

**Comment by sriumcp** [comment]
@sushmarchandran README.md documentation will also document how to use a specific version of Iter8?
