### ISSUE TITLE
falied while installing the iter8

### ISSUE THREAD

**Issue by CodelifeLyu** [iter8-tools/iter8#781]
**Describe the bug**
It gives me the error when installing K8s stack and Iter8.

**To Reproduce**
I following the quick start guide for iter8 and it works well until I am in step3.
It as me to setup Iter8 to my cluster.
the command line is "$ITER8/samples/istio/quickstart/platformsetup.sh"

**Expected behavior**
It should be successfully installed.

**Screenshots**
![71382876c31937c5bd3b6fd75915275](https://user-images.githubusercontent.com/77319993/121739354-12d7d180-cb2e-11eb-979f-39c8ba3cec38.png)
![963e28b657b4d84e65d9463c5b09876](https://user-images.githubusercontent.com/77319993/121739361-1408fe80-cb2e-11eb-8306-984f654a11a8.png)

**Comment by sriumcp** [comment]
It seems like `Kustomize` is not installed on your machine at a known path? Could you please try the binary install of Kustomize? 

Looks like you installed kustomize from Go source and it is not installed cleanly? Perhaps try the binary install:
```shell
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
```

(from https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/)
