### ISSUE TITLE
Recommendation: use -allow-initial-errors option in fortio.yaml

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#793]
**Is your feature request related to a **problem**? Please describe the **problem**.**
I observed that the fortio container will terminate if there is an error trying to send traffic. This was observed on OpenShift and when working with linkerd.

**Describe the feature/solution you'd like**
Use of the option `-allow-initial-errors` seems to address this problem.

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Tutorial test cases won't fail

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Make tutorials more robust

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
You can use this issue thread, or a discussion thread in this repo, for design discussions. Please provide the appropriate links. You can use the issue/discussion to also discuss and describe alternatives.

**How will this feature be tested?**
- [ ] Existing tutorials/test cases still run

**How will this feature be documented?**
Not needed

**Additional context**
This does not appear to be crtitical to update in all fortio.yaml files but it seems worth the effort in case the reason is environment or load related -- something we can't control in user clusters.

**Comment by kalantar** [comment]
@Alan-Cha

**Comment by kalantar** [comment]
@sriumcp Is this also relevant to the task `metric/collect` ?

**Comment by sriumcp** [comment]
Yes, this is relevant to `metrics/collect`... we can try creating an invalid target to test `metrics/collect` (I'm not sure what the current behavior is), and then create issues for its enhancement if anything is needed (example, change the Fortio flags it uses or add another task input or both)

**Comment by sriumcp** [comment]
subsumed by #940
