### ISSUE TITLE
Simplify finish action for promotion

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#798]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Experience shows that the use of (bash) script in the experiment is off-putting. We can create simple finish actions that replace the need for scripts. This issue is to create an action to do promotion via kubectl as described here.

**Describe the feature/solution you'd like**
Propose:

```yaml
      - task: common/promote-kubectl
        with:
          namespace: test
          manifest: "{{ .promotionManifest }}"
```
namespace parameter is target namespace of kubectl command
manifest is location of yaml file to use

Suggest naming `promote-kubectl` because anticipate will want to also have `promote-kustomize` and `promote-helm`.

Implementation can use `BashTask`.

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Simplify expression of finish action for promotion.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Simplify tutorials.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
This issue can serve this purpose.

**How will this feature be tested?**
- [x] tests for MakeTask and Run() work

**How will this feature be documented?**
- [ ] Document in References section
- [ ] Use in tutorials

**Comment by kalantar** [comment]
Iniitial implementation for discussion is here: https://github.com/iter8-tools/handler/pull/34.  It still needs test cases; but put here for discussion. Tried it in the linkerd experiment under development.  Test image is: `kalantar/iter8-handler:202106221405`.

**Comment by sriumcp** [comment]
`kubectl` supports a variety of options:

```shell
Options:
      --all=false: Select all resources in the namespace of the specified resource types.
      --allow-missing-template-keys=true: If true, ignore any errors in templates when a field or map key is missing in
the template. Only applies to golang and jsonpath output formats.
      --cascade='background': Must be "background", "orphan", or "foreground". Selects the deletion cascading strategy
for the dependents (e.g. Pods created by a ReplicationController). Defaults to background.
      --dry-run='none': Must be "none", "server", or "client". If client strategy, only print the object that would be
sent, without sending it. If server strategy, submit server-side request without persisting the resource.
      --field-manager='kubectl-client-side-apply': Name of the manager used to track field ownership.
  -f, --filename=[]: that contains the configuration to apply
      --force=false: If true, immediately remove resources from API and bypass graceful deletion. Note that immediate
deletion of some resources may result in inconsistency or data loss and requires confirmation.
      --force-conflicts=false: If true, server-side apply will force the changes against conflicts.
      --grace-period=-1: Period of time in seconds given to the resource to terminate gracefully. Ignored if negative.
Set to 1 for immediate shutdown. Can only be set to 0 when --force is true (force deletion).
  -k, --kustomize='': Process a kustomization directory. This flag can't be used together with -f or -R.
      --openapi-patch=true: If true, use openapi to calculate diff when the openapi presents and the resource can be
found in the openapi spec. Otherwise, fall back to use baked-in types.
  -o, --output='': Output format. One of:
json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-as-json|jsonpath-file.
      --overwrite=true: Automatically resolve conflicts between the modified and live configuration by using values from
the modified configuration
      --prune=false: Automatically delete resource objects, including the uninitialized ones, that do not appear in the
configs and are created by either apply or create --save-config. Should be used with either -l or --all.
      --prune-whitelist=[]: Overwrite the default whitelist with <group/version/kind> for --prune
      --record=false: Record current kubectl command in the resource annotation. If set to false, do not record the
command. If set to true, record the command. If not set, default to updating the existing annotation value only if one
already exists.
  -R, --recursive=false: Process the directory used in -f, --filename recursively. Useful when you want to manage
related manifests organized within the same directory.
  -l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)
      --server-side=false: If true, apply runs in the server instead of the client.
      --template='': Template string or path to template file to use when -o=go-template, -o=go-template-file. The
template format is golang templates [http://golang.org/pkg/text/template/#pkg-overview].
      --timeout=0s: The length of time to wait before giving up on a delete, zero means determine a timeout from the
size of the object
      --validate=true: If true, use a schema to validate the input before sending it
      --wait=false: If true, wait for resources to be gone before returning. This waits for finalizers.
```

It would be very useful if the task supported two in particular ... apply a folder (`-f` already does this), and apply a folder recursively (`-R` option). Folder use-cases are already there in some of our tutorials (example, promote and reset VS).

**Comment by sriumcp** [comment]
Kustomize integration with `kubectl` is shot! And stuck at 2.0.x, so no point in using `kustomize via kubectl`. The `kustomize-apply` task is a much better since it can enable v4.

**Comment by kalantar** [comment]
Agree, added optional boolean field `recursive`
Namespace is also optional; defaults to namespace of the experiment.

**Comment by kalantar** [comment]
This is really a generic `kubectl apply` task. I wonder if it is  better to just rename it common/kubectl-apply?

**Comment by sriumcp** [comment]
@kalantar I understand the original motivation for this task (make the `common/bash` task for promotion less scary).

Given that we are now starting to document GitOps-y promotion as well as notification based promotion, I feel we are better off with `common/bash` (and subsequently `run`; see #954). We can continue to invest in order to improve `common/bash` more useful (rather than spreading out our efforts across several other tasks, such as this one).

***
We don't really need this task. We can simply use `common/bash` (and also urgently, drop `common/exec`).

**Comment by sriumcp** [comment]
Closing for now. Please reopen if you feel more discussion is warranted.
