### ISSUE TITLE
Simplify iter8ctl

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#850]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Iter8ctl needs simplification. In particular: 
* it needs to become a kubernetes client, so that there is no need for piping the experiment yaml from kubectl
* the Tekton CLI supports a `last` flag, so that you do not need to know the name of the last task you ran. Similarly, `iter8ctl` needs to support a `latest` flag so that experiment name need not be specified explicitly
* we also want to assert various conditions on the experiment using `iter8ctl` (example, completed, completed without failure, and so on)

**Describe the feature/solution you'd like**
1. `iter8ctl describe -l` : this command should describe the last experiment to have been created by the user in the cluster. Note the simplification over current iter8ctl usage: it eliminates the need for the user to know the experiment name. This is useful in every one of our tutorials, especially, the helm tutorial where experiment name has a random suffix.
2. `iter8ctl` is also a kubernetes client as implied by the above command. So, there is no need to run `kubectl get experiment <name> -o yaml | iter8ctl describe -f -` anymore. The command is substantially shorter.
3. `iter8ctl` should support assertions like this: `iter8ctl assert -l -c completed -c winnerFound`. It will exit with code 0 if assertions are satisfied. Else, it will exit with code 1 after printing an appropriate error message. This is useful for tutorial purposes, human interaction, as well as CI/CD/GitOps usage scenarios.

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
The benefits to the users over current usage are described above.

**How will this feature be tested?**
- [x] Existing tests will be modified for `describe` and new unit tests will be added for `assert` command.

**How will this feature be documented?**
- [x] Iter8 tutorials will showcase these commands.

**Additional context**
Making iter8ctl a K8s client was a piece of feedback we received after one of our recent presentations. This issue is about listening to this piece of useful feedback from community as well.

**Comment by kalantar** [comment]
>     2\. `iter8ctl` is also a kubernetes client as implied by the above command. So, there is no need to run `kubectl get experiment <name> -o yaml | iter8ctl describe -f -` anymore. The command is substantially shorter.

What does this command look like when the `-l` option is not selected? And what does it look like with assertions.

**Comment by kalantar** [comment]
I pulled and reviewed the help; It appears that one should use either `-l` or `-e` and perhaps `-n`. I suggest that we don't require the `-e`. That the name be an optional parameter without a flag. This will make it more like a kubectl command ... which is part of the intent of these changes (to make it a kubectl client).

I wonder also if lack of a name might imply `-l`.  So `iter8ctl describe` suffices for latest. And `iter8ctl assert -n bookinfo-iter8 quickstart-exp -c completed` is a more complex example for experiment quickstart-exp in ns bookinfo-iter8.

**Comment by sriumcp** [comment]
> What does this command look like when the -l option is not selected?

`iter8ctl describe -e exp -n ns`: describe the experiment named `exp` in the namespace ns. The `-n` flag is optional; namespace is assumed to be default if not specified.

`iter8ctl describe -l`: describe the last experiment created in any namespace. `-e` and `-n` flags, if specified, will be ignored.

`iter8ctl assert -e exp -n ns -c completed -c winnerFound`: assert that the experiment  has completed and  a winner has been found. Currently, these are the only two assertions supported. This list will be extended to support a variety of other assertions in the future based on the info in the experiment object. `-c` can be repeated one or more times in an assert command.

`iter8ctl assert -e exp -n ns -c completed,winnerFound` is also valid.

`iter8ctl assert -l -c completed` is also valid.

**Comment by kalantar** [comment]
Is the `-l` flag apply to all namespaces or just the ns specified by `-n`. I assume the latter. But the question came to mind as I read the help

**Comment by sriumcp** [comment]
When `-l` flag is used `-n` flag is ignored. I believe `--help` makes this clear (in the `-n` description). Happy to clarify further.

***

+1 for dropping `-e` and `-l`. 

However, could we please handle this as a separate issue? I need to understand how positional arguments (i.e., arguments without flags) work in cobra/spf13 in order to implement this feature. Given that it is going to require some significant learning on my part (which I am happy to do), could we merge this `iter8ctl` improvement now, and please put this improvement off until after the upcoming community meetup?

***

@kalantar FYI.

***

Actually, I take this back :) Positional arguments look simple enough. So I am modifying the PR now. The bulk of the work is probably in modification of the tests! Anyway, pushing this change shortly...

**Comment by sriumcp** [comment]
@kalantar Fixed as per your comments.

**Comment by sriumcp** [comment]
`iter8ctl describe exp -n ns`: describe the experiment named `exp` in the namespace ns. The `-n` flag is optional; namespace is assumed to be default if not specified.

`iter8ctl describe`: describe the last experiment created in any namespace. `-n` flag, if specified, will be ignored.

`iter8ctl assert exp -n ns -c completed -c winnerFound`: assert that the experiment has completed and  a winner has been found. Currently, these are the only two assertions supported. This list will be extended to support a variety of other assertions in the future based on the info in the experiment object. `-c` can be repeated one or more times in an assert command.

`iter8ctl assert exp -n ns -c completed,winnerFound` is also valid.

`iter8ctl assert -c completed` is also valid. The last experiment is used for assertions.

**Comment by sriumcp** [comment]
Done.
