### ISSUE TITLE
`iter8ctl` subcommand to debug metrics

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#865]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Are the metrics defined for an experiment correct, and is the metrics backend working the way you are expecting it to work? Every Iter8 experimenter goes through these questions and currently finding the answers to them is hard -- primarily, because querying metrics backend is a non-trivial activity.

**Describe the feature/solution you'd like**
```shell
iter8ctl query -m <metric-name> -n <metric-ns> -u <backend url> -e <experiment> -a <Iter8 analytics URL>
```

This will query the metrics backend URL using the given Iter8 metric, by filling in the metric template variables using the given experiment. It would show the raw output from the metrics backend URL and also show the result of applying the jq expression on top of the raw output.

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Help debug metrics in Iter8 experiments.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Accelerate the definition of metrics... this feature will make it easy to play with metric definitions quicker.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes (tbd).

**How will this feature be tested?**
- [ ] unit tested, and integration tested with iter8 analytics.

**How will this feature be documented?**
- [ ] iter8.tools documentation

**Comment by kalantar** [comment]
Is there anything else that can be queried? I suggest removing the `-m` flag.

Why is `backend_url` needed? I feel like this is already in the metric.

I feel like the challenge in accelerating development is in the writing of the query and the jqExpression. ln this light, it may be that a `-f manifest` may be appropriate combining the redefinition of the metric with the apply and the query all at once. Perhaps even obviating the need for the metric-name and namespace. 

I think the output should also show the raw query that will be sent and any header details. Perhaps a special flag for revealing the contents of interpolated secrets (which should not otherwise be exposed, I think. But not sure.

**Comment by sriumcp** [comment]
How about:

```shell
iter8ctl query -m <metric-manifest> -e <experiment-manifest> -a <Iter8 analytics UR; perhaps port forwarded>
```

1. Both experiment and metrics are now manifests (files available locally). It doesn't matter whether they're deployed or not, because the above command will only look at the local files, not the deployed resources.
2. Yes, spelling out the query that is sent, the intermediate results that came back from metrics backend, and the result of jq post-processing, and other relevant details is what would make this command shine.

**Comment by kalantar** [comment]
How about 

    iter8ctl query -f <metric-manifest> -f <experiment-manifest> -a <Iter8 analytics UR; perhaps port forwarded>

Repeated use of -f mirroring the kubectl CLI. Allows both to be specified in the same file or different ones. 

Is there a possibility that the metric/experiment will be in the cluster? Do we need to support both the manifeset and in cluster? I think for development of metrics, manifest makes most sense.

This suggestion is really to make it more similar to kubectl CLI so familiar interaction. But if distinguishing at cli level between is easier, -e and -m work too.

**Comment by sriumcp** [comment]
Both for dev and debugging purposes, manifest should be ok. If the metric and experiment is already in the cluster, you can always `kubectl get the iter8 metric -o yaml > metric-manifest.yaml`; same holds for the experiment.

Re: `-f` and `-f`, I feel both conceptually and implementation wise, `-m` and `-e` is easier as it makes it clear what is what. Perhaps, we can allow both the `metrics-manifest` and `experiment-manifest` to be the same underlying file? So, user still has the option of using a single file for both.

**Comment by kalantar** [comment]
sounds good.

**Comment by sriumcp** [comment]
Obsolete.
