### ISSUE TITLE
Trigger Helm repo update within Iter8 CI automatically

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#872]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Helm repo updates are currently manual and human-intensive.

**Describe the feature/solution you'd like**
Whenever code is pushed to Iter8's helm folder (helm), the helm repo update workflow needs to be triggered automatically.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Make Iter8 Helmex development less human-intensive.

**Additional context**
This is a simple change to Iter8 CI.

**Comment by sriumcp** [comment]
@Alan-Cha Do you want to take this on? Helm repo upgrade is actually needed now for the linkerd tutorial to work. I will do this manually for now.

**Comment by Alan-Cha** [comment]
Yes, I will take a look at this. I have been taking a look at the other GitHub workflows as well recently.

**Comment by sriumcp** [comment]
Obsolete.
