### ISSUE TITLE
`iter8ctl` subcommand to debug experiments

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#908]
**Is your feature request related to a **problem**? Please describe the **problem**.**
If something goes wrong during an experiment (example, missing metric definition or task failure) ... users will need help debugging. Currently, there is no easy way to do this other than looking into experiment status and raw logs. The former is complex and difficult to parse for humans (e.g., there are no conditions for success or failures currently; only reasons supplied as part of completed condition); the latter is nearly impossible to parse for humans.

**Describe the feature/solution you'd like**
```shell
iter8ctl debug # optionally, -e <experiment-name> -n <experiment-namespace>
```

This will print a few carefully selected log messages from handler jobs, analytics service, and etc3 for this experiment. Of course, log format needs to be designed carefully for this debugging to make sense (plainly dumping the current logs on users is not an option, because they are unreadable).

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Help debug iter8 experiments effectively.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Accelerate development of tutorials, and debugging of issues in Iter8 components.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
1. Any log line in `handler`, `etc3` or `iter8-analytics` that includes the word `iter8-log` will be filtered in for printing by `iter8ctl debug`. All other logs will be filtered out.
2. `iter8-log` lines will always include experiment name and namespace. This enables `iter8ctl` to filter in logs for a specific experiment from etc3 and analytics and filter out everything else.
3. `iter8-log` lines will always include `loop: <loop num> iteration: <iteration name>`. This enables logs from `handler`, `etc3` and `iter8-analytics` to be sorted correctly by `iter8ctl`. Sorting by timestamp is not an option since time it is not synchronized across the three components..
4. `loop` and `iteration` numbers above will always appear in the same (consistent) field position in `iter8-ctl` logs to facilitate sorting (for example, if analytics prints loop counter in position 5, it will always use position 5; etc3 prints loop counter in position 6, it will always use position 6). Output will always be sorted by loop and iteration counters and sorting will be handled internally by `iter8ctl`.
5. [this does not impact iter8ctl] All `iter8-log` lines will have `verbosity: <int>` value set between 1 and 10. We can figure out what the right level of detail for the right log message is. This enables ... 
```shell
iter8ctl debug |  grep "verbosity: 5"
```
6. [this does not impact iter8ctl] Logs from handler will include `action: start` (or loop or finish), and task name... 
```shell
iter8ctl debug |  grep "verbosity: 5" | grep "action: finish" | grep "task: notification/http"
```
7. [this does not impact iter8ctl] Logs from handler, etc3 and analytics will include their source ... 
```shell
iter8ctl debug |  grep "verbosity: 5" | grep "source: analytics"
```
8. The above rules do not impact log lines in Iter8 components that do not include the `iter8-log` keyword in them.

All of the above should enable the user to easily control the type of log and the level of detail of the log that they see.... 

**How will this feature be tested?**
- [ ] unit tested, and integration tested to ensure logs can be pulled from all iter8 components.

**How will this feature be documented?**
- [ ] iter8.tools documentation
- [ ] iter8ctl CLI documentation

**Comment by sriumcp** [comment]
Use cases (root causing experiment failures...)
1. Token missing
2. Secret missing
3. Readiness check failed
4. RBAC permissions insufficient for some handler task
5.  Some resource (example metric or some other domains resource) referenced in the experiment is absent
6. ...

**Comment by kalantar** [comment]
6. Any handler failure 
    a. notification/http POST fails -- what is response message?
7. metric values are undefined
    a. no load?
    b. invalid metric definition?
    c. information missing in definition?
    d. metrics backend not working?
8. one of the experiment validation fails
9. clearer messages
10. better logs; configurability of amount of logs
11. Neither task nor run specified in the task spec 
12. ...

**Comment by kalantar** [comment]
I have been reflecting on my personal process of debugging Iter8 experiments. A key first step that allows me to ignore many irrelevant details is to get a general idea of what the problem is. Is it a validation problem? Is it in a task?  Which task? Is it a metric? Is it the interaction with the analytics service?  Did it go through any loops? To gain this insight, I find that the list of kubernetes events (available from `kubectl describe experiment` gives the quickest insight today. I think something similar would be valuable.

**Comment by sriumcp** [comment]
Could you please describe what `kubectl describe experiment` gives which is not present in the above list? 
***
Personally, I have not found `kubectl describe` especially useful. For most errors, I have had to dig deeper into logs (which are themselves unreadable and certainly not worthy of being dumped directly on an end-user).

Having said that, I would like to understand precisely what `kubectl describe experiment` gives today which is missing in the design of `iter8ctl debug`.

**Comment by kalantar** [comment]
Today `kubectl describe` lists the events that have been issued. Errors are usually explicitly listed. This is more useful than the message you see with `kubectl get` since this is the message from the last event. The actual error is overwritten by a geneic "failed" event.  Further, the list of events indicates where in the process the error occurred.

In thinking about this in the context of a controller-less experiment, a list of progress through the tasks would be valuable. What are the specified tasks and what progress was made. This identifies the task to start investigation.

**Comment by sriumcp** [comment]
1. Supplying an improper token can result in `-run` task not completing properly. But the debug output in this scenario doesn't reveal the issue. The run script fails due but the STDERR from the failing execution is lost
2. Supplying a GitHub Actions workflow that is not in the specified branch also has similar issues as above
3. Some errors seem to be printed twice (example, missing resource name in `with: secret:` field
4. Action type and task names are required but missing in output.
5. Token is visible in clear text
6. While not strictly a `debug` issue, when an experiment fails, the failure condition needs to be reflected by `iter8ctl describe` output.
