### ISSUE TITLE
getting-started/first-experiment deploys an experiment with the baseline version

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#914]
**Describe the bug**
When executing the documented `first-experiment`, the first `helm install` command also installs an experiment object. This leads to potential issues such as start handler failure if the second is not deployed quickly enough. In my test, I saw one instance of the job fail. Fortunately, it succeeded on the second.
Further, when the final `helm upgrade` is executed, the experiment was not deleted as expected.

**To Reproduce**
Steps to reproduce the behavior. For example:
1. Go to https://iter8.tools/0.7/getting-started/first-experiment/
2. Follow setup instructions and execute first helm command.
3. Observe that an experiment was created

You can also verify by executing the following and inspecting the output:

    helm template my-app . \
      --set baseline.dynamic.tag=1.0 \
      --set candidate=null 

**Expected behavior**
No experiment should be created

**Kubernetes environment (please provide the following information):**
 - IKS cluster

**Comment by sriumcp** [comment]
We will fix this using the following three PRs:
1. Change the `deploy` Helm chart in Iter8 (the one under `$ITER8/helm` folder). Write an e2e test for this chart. (PR1)
2. Once the above PR is merged, update the chart in Iter8 Helm repo
3. Once the chart is updated, fix the tutorial, and delete the `samples/first-exp` folder (PR2)
4. Tag and release a new version of Iter8 (PR3)

**Comment by sriumcp** [comment]
Fixed.
