### ISSUE TITLE
Use fortio -ignore-initial-errors option in metrics/collect task

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#918]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Some experiments fail because fortio fails early. One strategy to avoiding some errors (caused by cold start) is use of the `-ignore-initial-errors` option in fortio. This adds a measure of resilience to the task even though it won't solve every issue.

**Describe the feature/solution you'd like**

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Task more resilient

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Can do here. Should be just a couple of lines added to the [method `resultForVersion`](https://github.com/iter8-tools/handler/blob/main/tasks/lib/metrics/collect.go#L230).

**How will this feature be tested?**
- [ ] existing tests pass

**How will this feature be documented?**
No need

**Additional context**
As an example, this seemed particularly useful when writing the linkerd tutorial.

**Comment by sriumcp** [comment]
This issue is subsumed by #940
