### ISSUE TITLE
Document `iter8ctl` kubeconfig

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#920]
**Description:**

`iter8ctl` kubeconfig relies on https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client/config#hdr-Config_precedence

Options 1 and 3 in the precedence list is not relevant for `iter8ctl` CLI, but 2 and 4 are. This needs to be documented clearly.

**Documentation links:**

It would be nice to not just have CLI documentation for `iter8ctl` but also iter8.tools documentation.

**Comment by sriumcp** [comment]
@kalantar I know you were running into `iter8ctl` kubeconfig issues earlier. Is it sorted out? This documentation issue still remains, but curious if you were able to get `iter8ctl` working as expected.

**Comment by kalantar** [comment]
> I know you were running into `iter8ctl` kubeconfig issues earlier. Is it sorted out?

Not yet. I did verify that @huang195 was NOT having a problem with a remote Openshift cluster. My kubeconfig is a bit of a mess. I plan to clean it up and try again. I will let you know if it remains an issue.

**Comment by kalantar** [comment]
I checked again and still do not have access. To replicate. Login to cloud.ibm.com and create a cluster. Login to the cluster using the instructions "Connect via CLI". Verify works by executing kubectl commands. Execute `iter8ctl describe`. Get this error `Error: cannot get client using rest config`.

**Comment by kalantar** [comment]
Perhaps this issue is related to the need for client auth plugins. IKS uses OIDC. We may be importing some and not others. I notice that kubebuilder now adds this line to add all of them:

	// Import all Kubernetes client auth plugins (e.g. Azure, GCP, OIDC, etc.)
	// to ensure that exec-entrypoint and run can make use of them.
	_ "k8s.io/client-go/plugin/pkg/client/auth"

**Comment by kalantar** [comment]
> Perhaps this issue is related to the need for client auth plugins

It appears that is is the problem. PR https://github.com/iter8-tools/iter8ctl/pull/37 seems to fix it.

**Comment by sriumcp** [comment]
Fixed.
