### ISSUE TITLE
Upgrade kubebuilder from v2 to v3

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#921]
**Is your feature request related to a **problem**? Please describe the **problem**.**
No.

**Describe the feature/solution you'd like**
Upgrade version of kubebuilder from v2 to v3.

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Will address some security issues.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Keep code more current avoiding larger problems later on.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
No

**How will this feature be tested?**
- [ ] current tests should pass

**How will this feature be documented?**
No need

**Additional context**
Migration guide is here: https://book.kubebuilder.io/migration/migration_guide_v2tov3.html

**Comment by sriumcp** [comment]
Can this be closed @kalantar ?
