### ISSUE TITLE
Restructure packages in etc3

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#923]
**Is your feature request related to a **problem**? Please describe the **problem**.**
No. Currently, etc3 has a number of helper packages "analytics", "configuration" and "util". In principle, the purpose was to separate distinct function. In practice there is one small file in each package. While we are upgrading kubebuilder and making the move to v2alpha3 I suggest we simplify the package structure by combining them all in the controllers package.

**Describe the feature/solution you'd like**
Combine them together leaving just 2 pacakges `api/v2alpha?` and `controllers`

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
No.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Simplify code base.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Not really.

**How will this feature be tested?**
- [ ] Current tests should work

**How will this feature be documented?**
No need

**Comment by kalantar** [comment]
@sriumcp any thoughts?

**Comment by sriumcp** [comment]
SGTM @kalantar

**Comment by sriumcp** [comment]
@kalantar I request that we also add `area/controller` labels to controller issues.
