### ISSUE TITLE
Remove "Template" from URLTemplate and HeaderTemplates

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#930]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Purpose is to make the names "nicer". Yes, they are templates in that they can have parameters. However, I would prefer simpler names `URL` and `Headers`. 

**Describe the feature/solution you'd like**
Rename `URLTemplate` to `URL` and `HeaderTemplates` to `Headers.

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Maybe easier to understand. Shorter.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
No

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Do so here.

**How will this feature be tested?**
- [ ] Existing (modified) test cases should work

**How will this feature be documented?**
- [ ] Update reference documentation

**Additional context**
Suggestion is being made because changes are breaking and we have changes for Experiment as well. Might as well make more breaking changes at the same time.

**Comment by sriumcp** [comment]
SGTM.

**Comment by sriumcp** [comment]
This issue is now superceded by #934
