### ISSUE TITLE
Replace `common/bash` with `run`

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#954]
**Is your feature request related to a **problem**? Please describe the **problem**.**
`common/bash` is proving to be useful and a real workhorse. However, it requires at least three lines to specify at the moment instead of a single line.

**Describe the feature/solution you'd like**

Replace `common/bash` with `run`. Please see #960

**Comment by sriumcp** [comment]
**Note:** Please see #942

**Comment by kalantar** [comment]
@sriumcp is this issue completed? Can it be closed?

**Comment by kalantar** [comment]
> is this issue completed?

I guess not; removal of bash is still necessary. I will do this as part of v0.8

**Comment by kalantar** [comment]
I think we want to remove `common/exec` as well, no?

**Comment by sriumcp** [comment]
Yes.
