### ISSUE TITLE
Simplify experiment status

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#961]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Experiment status has currently too many unused / unnecessary fields, complicating the UX for the fields that are actually useful / necessary.

**Describe the feature/solution you'd like**
1. `startTime == initTime` (see #949). So, drop `initTime` and remove `Waiting` as a stage.
2. Include `completedLoops`. This is akin to `completedIterations`. 
3. 
```go
type CurrentWeightDistribution []int32 // no need for version names, which come from `Spec.VersionNames`
```
4. Drop `versionRecommendedForPromotion` (please see the need to keep things simple and the need to avoid very complex UX like dynamic version-specific interpolation). #941 
5.
```go
type Status struct {
...
Analysis Analysis
}
```

```go
type Analysis struct {
// if not nil, length of the slice must match length of versionNames
Metrics []VersionMetrics
// If not nil, length of the outer slice must match length of versionNames
// If not nil, length of inner slice must match number of objectives
Objectives [][]bool 
// if not nil, length of the slice must match length of versionNames
Weights []int32
Winner Winner
}
```

```go
type Winner struct {
  WinnerFound bool
  // must match a versionName if `WinnerFound == true`. 
  Winner *string 
}
```

```go
// instead of a single value, we want to store a list; see #911 
// map from a version name to a slice of quantities
type VersionMetricts map[string][]Quantity
```

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Make experiment status readable by humans. Currently it is not.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
This simplifies `iter8-analytics` substantially for `v2beta1`.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes. Please see above. Testing and documentation will be as-is (with appropriate changes).

**Comment by kalantar** [comment]
> The following sample was provided:
```yaml
type Status struct {
...
Analysis Analysis
}
```
Does this imply Analysis is a required field?  In the past, we had `Analysis *Analysis` (it was optional).

**Comment by kalantar** [comment]
We currently have a field `Analysis.AggregatedBuiltinHists` (documented as *aggregated builtin metrics will be derived from this data structure*). It is not present in the sample above. Should it be?

**Comment by kalantar** [comment]
> The following sample was provided above:
```yaml
// instead of a single value, we want to store a list; see #911 
type VersionMetricts map[string][]Quantity
```
What is the key *string*? In the past, we had min/max/value/samplesize. Are we reducing to just value?

**Comment by sriumcp** [comment]
`string` is the name of the version. Must match a name appearing in the experiment's `Spec.VersionInfo` list (of names).

**Comment by kalantar** [comment]
> `string` is the name of the version. Must match a name appearing in the experiment's `Spec.VersionInfo` list (of names).

The proposed model is: 
```yaml
type Analysis struct {
// if not nil, length of the slice must match length of versionNames
Metrics []VersionMetrics
...
// instead of a single value, we want to store a list; see #911 
type VersionMetricts map[string][]Quantity
```
I would think the version is implicit (ie, order based) in the list of VersionMetrics (as for everything else in `Analysis`. The `string` index of the map must be the metric name? What is the list of values we are storing?  Our old model had 3 values (min/max/value).

**Comment by sriumcp** [comment]
Sorry @kalantar You are right of course. `string` is the name of the metric. There will be no more `min/max/value`. Far more information is available now in metrics, because we're storing a list of all observations. 

This means, we're not storing the min, max, or the latest observation explicitly (all of these can be derived from list if needed).

**Comment by kalantar** [comment]
@sriumcp so... the list of values is the list of values observed during the current observation window?  Or is it meant to be historical as well (I think we discussed this .. but perhaps it is a future issue)

Does this eliminate the need for buildinHists?

**Comment by sriumcp** [comment]
@kalantar It is a list of values observed historically (not just the current window).

Yes, it eliminates the need for `builtInHists` (which is a bit of a ugly hack for built in metrics). (so, we can drop this field from status).

**Comment by kalantar** [comment]
PR https://github.com/iter8-tools/etc3/pull/232 addresses item 1 
PR https://github.com/iter8-tools/etc3/pull/233 addresses items 3 and 5
PR https://github.com/iter8-tools/etc3/pull/234 addresses item 2
PR https://github.com/iter8-tools/etc3/pull/235 addresses item 4

**Comment by sriumcp** [comment]
In order to support #1008 ... 

```go
type VersionMetricts map[string][]Quantity
```

***

alternative 1:

```go
type VersionMetricts struct {
  Values map[string][]MetricVal
  Aggregations map[string]Quantity
}

type MetricVal struct {
  Quantity // embedded struct -- quantity is used for every type of metric -- sample, histogram, gauge, and counter
  lower *Quantity //  this is non-nil only for a histogram metric
  upper *Quantity // this is non-nil only for a histogram metric  
}
```

***

alternative 2:

```go
type VersionMetricts struct {
  Values map[string][]Quantity
  Buckets map[string][]Bucket
  Aggregations map[string]map[string]Quantity
}

type Bucket struct {
  lower *Quantity
  upper *Quantity
}
```

***

alternative 3:

```go
type VersionMetricts map[string]struct {
  Values []Quantity
  Buckets []Bucket
  Aggregations map[string]Quantity
}

type Bucket struct {
  lower *Quantity
  upper *Quantity
}

```

**Comment by kalantar** [comment]
Example of alternative 3 (seems to be the best):

```yaml
  metrics: # alternative 3
  # default version
  - error-rate:
      values: ["0", "0", "0", "0", "0"]
    backend/mean-latency:
      values: [197500m, 187500m, 177500m, 167500m, 197500m]
    hist:
      values: [12, 15, 25]
      buckets: [{lower: 1, upper: 10}, {lower: 11, upper: 20}, {lower: 21, upper: 30}]
    aggregation-metric1:
      values: [1,2,3,4]
      aggregations:
        sum: 10
        percentile-99: 1
    aggregation-metric2:
      values: [7, 8, 9,20]
      aggregations:
        sum: 44
        percentile-99: 2
  # canary version
...
```

**Comment by kalantar** [comment]
Reconsideration of design. Reopening issue.
