### ISSUE TITLE
Remove Spec.Strategy

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#969]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Issue https://github.com/iter8-tools/iter8/issues/941 included several changes in addition to removing `Spec.VersionInfo`. This issue documents them: 
- removal of `Spec.Strategy.DeploymentPattern` and `Spec.Strategy.Weights`
- move `Spec.Strategy.Actions` to `Spec.Actions`
- delete `Spec.Strategy`

**Describe the feature/solution you'd like**
See above

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Simplifies experiment

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Use this issue .

**How will this feature be tested?**
- [ ] modify existing test cases

**How will this feature be documented?**
- [ ] Reference documentation to be updated

**Comment by kalantar** [comment]
Do we really want to remove `Spec.Strategy.Weights`?

**Comment by sriumcp** [comment]
Yes. Weight shifting will happen in a task, which means any inputs for weight shifting needs to be colocated with the task (as usual, using a `with` clause).

Sprinkling a little bit of weight information all over the CR doesn't help the user in anyway.

**Comment by kalantar** [comment]
A field in `Objective` is: 
```yaml
// RollbackOnFailure indicates that if the criterion is not met, the experiment should be ended
// default is false
// +optional
RollbackOnFailure *bool `json:"rollback_on_failure,omitempty" yaml:"rollback_on_failure,omitempty"`
```
I don't think we have ever used this. All the related logic is predicated on `Spec.Strategy.DeploymentPattern` (when bluegreen ...).  I believe we should eliminate this field and related behavior as well.  Any thoughts?

**Comment by sriumcp** [comment]
Please eliminate this field for now.

There is an early termination behavior we want to introduce, but at this stage we don't even know how and haven't designed for it yet. If and when we design it, it can easily be made as a non-version breaking change.
